[package]
name = "server_admin_core"
version.workspace = true
publish.workspace = true
description = "Administrator domain wrapper types and invariants"
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
optimal_memory_layout = { workspace = true }
newtype = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
server_admin_contract = { workspace = true }
str_constants = { workspace = true }
thiserror = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
usize_constants = { workspace = true }

[lints]
workspace = true
