[package]
name = "gen_pg_json_obj_test"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
description = "PostgreSQL JSON object generator test support"
repository = "https://github.com/kuqmua/rust_workspace_template"
readme = "../../../README.md"
keywords = ["postgres", "tests"]
categories = ["development-tools"]

[dev-dependencies]
gen_pg_json_obj_src.workspace = true
macro_clippy_check_cmn = { workspace = true, features = ["test-utils"] }
quote.workspace = true

[features]
test-utils = ["macro_clippy_check_cmn/test-utils"]

[lints]
workspace = true
