[package]
name = "panic_location"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dependencies]
optimal_memory_layout = { workspace = true }
str_constants = { workspace = true }
newtype = { workspace = true }
to_err_string = { workspace = true }

[lints]
workspace = true
