proc_macro_frontend_contract_route_registry::route_registry! {
    #[openapi(
        tags((name = "admin_auth", description = "Administrator authentication and sessions"), (name = "admin_users", description = "Administrator user security operations"), (name = "admin_roles", description = "Administrator role security operations"), (name = "admin_audit", description = "Administrator audit log"), (name = "admin_settings", description = "Administrator system settings"), (name = "admin_tables", description = "Read-only administrator database views"))
    )]
    pub(crate);
    state = crate::shared_admin_auth_svc_state_arc::SharedAdminAuthSvcStateArc,
    family = server_admin_contract::admin_route::AdminAuthenticationRouteFamily;
    (constants_str::ADMIN_COOKIE, constants_str::ADMIN_CSRF);
    schemas(
        server_admin_contract::positive_non_zero_i64::PositiveNonZeroI64,
        server_admin_contract::admin_permission_values::AdminPermissionValues,
        server_admin_contract::admin_role_names::AdminRoleNames,
        server_admin_contract::admin_role_ids::AdminRoleIds,
        server_admin_contract::admin_permission_ids::AdminPermissionIds,
        server_admin_contract::admin_user_summaries::AdminUserSummaries,
        server_admin_contract::admin_role_summaries::AdminRoleSummaries,
        server_admin_contract::admin_permission_summaries::AdminPermissionSummaries,
        server_admin_contract::admin_audit_views::AdminAuditViews,
        server_admin_contract::admin_texts::AdminTexts,
        server_admin_contract::admin_data_column::AdminDataColumn,
        server_admin_contract::admin_data_columns::AdminDataColumns,
        server_admin_contract::admin_data_filter::AdminDataFilter,
        server_admin_contract::admin_data_filters::AdminDataFilters,
        frontend_contract::input_kind::InputKind,
        server_admin_contract::admin_data_rows::AdminDataRows,
        server_admin_contract::admin_data_tables::AdminDataTables,
        server_admin_contract::admin_optional_settings::AdminOptionalSettings,
        server_admin_contract::admin_session_views::AdminSessionViews,
        server_admin_contract::admin_session_view::AdminSessionView,
        server_admin_contract::admin_session_timestamp::AdminSessionTimestamp,
        server_admin_contract::admin_session_identifier::AdminSessionIdentifier,
        server_admin_contract::admin_text::AdminText,
        server_admin_contract::admin_bool::AdminBool,
        server_admin_contract::admin_permission_value::AdminPermissionValue,
        server_admin_contract::admin_new_password::AdminNewPassword,
        server_admin_contract::admin_audit_view::AdminAuditView,
        server_admin_contract::admin_audit_timestamp::AdminAuditTimestamp,
        server_admin_contract::admin_audit_log_id::AdminAuditLogId,
        server_admin_contract::serde_json_admin_audit_details::SerdeJsonAdminAuditDetails,
        server_admin_contract::admin_optional_setting::AdminOptionalSetting,
        server_admin_contract::admin_default_route::AdminDefaultRoute,
        server_admin_contract::admin_main_logo::AdminMainLogo,
        server_admin_contract::admin_organization_contacts::AdminOrganizationContacts,
        server_admin_contract::admin_organization_name::AdminOrganizationName,
        server_admin_contract::admin_primary_color::AdminPrimaryColor,
        server_admin_contract::admin_site_name::AdminSiteName,
        server_admin_contract::admin_support_url::AdminSupportUrl,
        server_admin_contract::admin_tab_title::AdminTabTitle,
        server_admin_contract::admin_user_summary::AdminUserSummary,
        server_admin_contract::admin_role_summary::AdminRoleSummary,
        server_admin_contract::admin_permission_summary::AdminPermissionSummary,
        server_admin_contract::admin_data_table::AdminDataTable,
        server_admin_contract::admin_data_row::AdminDataRow,
        server_admin_core::uuid_admin_value::UuidAdminValue,
        crate::runtime_admin_password::RuntimeAdminPassword,
        server_admin_contract::admin_login::AdminLogin,
        server_admin_contract::admin_display_name::AdminDisplayName,
        server_admin_contract::admin_role_name::AdminRoleName,
        server_admin_core::admin_user_record_id::AdminUserRecordId,
        server_admin_core::admin_role_record_id::AdminRoleRecordId,
        server_admin_contract::admin_permission::AdminPermission,
        crate::admin_session_id::AdminSessionId,
        crate::admin_audit_action::AdminAuditAction,
        crate::admin_audit_resource::AdminAuditResource
    );
    (server_admin_contract::admin_sign_in_route::AdminSignInRoute, crate::api_sign_in::api_sign_in),
    (server_admin_contract::admin_refresh_route::AdminRefreshRoute, crate::api_refresh::api_refresh),
    (server_admin_contract::admin_sign_out_route::AdminSignOutRoute, crate::api_sign_out::api_sign_out),
    (server_admin_contract::admin_me_route::AdminMeRoute, crate::api_me::api_me),
    (server_admin_contract::admin_change_own_password_route::AdminChangeOwnPasswordRoute, crate::api_change_own_password::api_change_own_password),
    (server_admin_contract::admin_sessions_route::AdminSessionsRoute, crate::api_sessions::api_sessions),
    (server_admin_contract::admin_revoke_session_route::AdminRevokeSessionRoute, crate::api_revoke_session::api_revoke_session),
    (server_admin_contract::admin_revoke_all_sessions_route::AdminRevokeAllSessionsRoute, crate::api_revoke_all_sessions::api_revoke_all_sessions),
    (server_admin_contract::admin_create_user_route::AdminCreateUserRoute, crate::api_create_user::api_create_user),
    (server_admin_contract::admin_update_users_route::AdminUpdateUsersRoute, crate::api_update_users::api_update_users),
    (server_admin_contract::admin_delete_users_route::AdminDeleteUsersRoute, crate::api_delete_users::api_delete_users),
    (server_admin_contract::admin_create_roles_route::AdminCreateRolesRoute, crate::api_create_roles::api_create_roles),
    (server_admin_contract::admin_update_roles_route::AdminUpdateRolesRoute, crate::api_update_roles::api_update_roles),
    (server_admin_contract::admin_delete_role_route::AdminDeleteRoleRoute, crate::api_delete_role::api_delete_role),
    (server_admin_contract::admin_set_role_permissions_route::AdminSetRolePermissionsRoute, crate::api_set_role_permissions::api_set_role_permissions),
    (server_admin_contract::admin_list_permissions_route::AdminListPermissionsRoute, crate::api_list_permissions::api_list_permissions),
    (server_admin_contract::admin_audit_log_route::AdminAuditLogRoute, crate::api_audit_log::api_audit_log),
    (server_admin_contract::admin_audit_export_route::AdminAuditExportRoute, crate::api_export_audit_log::api_export_audit_log),
    (server_admin_contract::admin_branding_route::AdminBrandingRoute, crate::api_branding::api_branding),
    (server_admin_contract::admin_settings_route::AdminSettingsRoute, crate::api_settings::api_settings),
    (server_admin_contract::admin_update_settings_route::AdminUpdateSettingsRoute, crate::api_update_settings::api_update_settings),
    (server_admin_contract::admin_data_tables_route::AdminDataTablesRoute, crate::api_data_tables::api_data_tables),
    (server_admin_contract::admin_data_table_route::AdminDataTableRoute, crate::api_data_table::api_data_table),
    (server_admin_contract::admin_user_roles_table_route::AdminUserRolesTableRoute, crate::api_user_roles_table::api_user_roles_table),
    (server_admin_contract::admin_role_permissions_table_route::AdminRolePermissionsTableRoute, crate::api_role_permissions_table::api_role_permissions_table),
    (server_admin_contract::admin_refresh_tokens_table_route::AdminRefreshTokensTableRoute, crate::api_refresh_tokens_table::api_refresh_tokens_table),
    (server_admin_contract::admin_access_sessions_table_route::AdminAccessSessionsTableRoute, crate::api_access_sessions_table::api_access_sessions_table),
    (server_admin_contract::admin_login_attempts_table_route::AdminLoginAttemptsTableRoute, crate::api_login_attempts_table::api_login_attempts_table),
    (server_admin_contract::admin_rate_limits_table_route::AdminRateLimitsTableRoute, crate::api_rate_limits_table::api_rate_limits_table),
    (server_admin_contract::admin_cleanup_status_table_route::AdminCleanupStatusTableRoute, crate::api_cleanup_status_table::api_cleanup_status_table),
}
