proc_macro_frontend_contract_route_registry::route_registry! {
    pub(crate);
    state = crate::shared_admin_auth_svc_state_arc::SharedAdminAuthSvcStateArc;
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::Health, crate::admin_health_page::admin_health_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::Branding, crate::admin_branding_page::admin_branding_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::CleanupStatusRead, crate::cleanup_status_read_page::cleanup_status_read_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::SignIn, crate::sign_in_page::sign_in_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::SystemSettingRead, crate::system_setting_read_page::system_setting_read_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::Tables, crate::data_tables::data_tables),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::PermissionActionRead, crate::permission_action_read_page::permission_action_read_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::PermissionResourceActionRead, crate::permission_resource_action_read_page::permission_resource_action_read_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::PermissionResourceRead, crate::permission_resource_read_page::permission_resource_read_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::AccessSessionRead, crate::access_session_read_page::access_session_read_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::AuditLogRead, crate::audit_log_read_page::audit_log_read_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::LoginAttemptRead, crate::login_attempt_read_page::login_attempt_read_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::RefreshTokenRead, crate::refresh_token_read_page::refresh_token_read_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::Users, crate::users::users),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::UsersCreate, crate::users_create_page::users_create_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::UsersManage, crate::users_manage_page::users_manage_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::UserRoleRead, crate::user_role_read_page::user_role_read_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::RoleRuleRead, crate::role_rule_read_page::role_rule_read_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::UserRead, crate::user_read_page::user_read_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::RoleRead, crate::role_read_page::role_read_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::Roles, crate::roles::roles),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::RolesCreate, crate::roles_create_page::roles_create_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::RolesManage, crate::roles_manage_page::roles_manage_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::RuleRead, crate::rule_read_page::rule_read_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::Rules, crate::rules::rules),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::Sessions, crate::admin_html_sessions_page::admin_html_sessions_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::Profile, crate::profile::profile),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::RateLimitRead, crate::rate_limit_read_page::rate_limit_read_page),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::Settings, crate::settings::settings),
    (server_admin_contract::admin_frontend_path::AdminFrontendPath::Version, crate::version::version),
}
