#[path = "application_users_mutations_create.rs"]
pub(super) mod mutations_create;
#[path = "application_users_mutations_delete.rs"]
pub(super) mod mutations_delete;
#[path = "application_users_mutations_set_ban.rs"]
pub(super) mod mutations_set_ban;
#[path = "application_users_mutations_set_password.rs"]
pub(super) mod mutations_set_password;
#[path = "application_users_mutations_set_roles.rs"]
pub(super) mod mutations_set_roles;
#[path = "application_users_mutations_update.rs"]
pub(super) mod mutations_update;
#[path = "application_users_queries_list.rs"]
pub(super) mod queries_list;
#[path = "application_users_queries_users_page.rs"]
pub(super) mod queries_users_page;
