#[path = "mutations_set_permissions.rs"]
pub(super) mod mutations_set_permissions;
#[path = "queries_list_permissions.rs"]
pub(super) mod queries_list_permissions;
#[path = "queries_roles_page.rs"]
pub(super) mod queries_roles_page;
#[path = "role_mutations_create.rs"]
pub(super) mod role_mutations_create;
#[path = "role_mutations_delete.rs"]
pub(super) mod role_mutations_delete;
#[path = "role_mutations_update.rs"]
pub(super) mod role_mutations_update;
#[path = "role_queries_list.rs"]
pub(super) mod role_queries_list;
