// Root-owned module compatibility wrappers.
mod sign_in_form {}
mod change_password_form {}
mod revoke_session_form {}
mod create_user_form {}
mod update_user_form {}
mod user_password_form {}
mod user_ban_form {}
mod user_id_form {}
mod user_roles_form {}
mod create_role_form {}
mod update_role_form {}
mod role_id_form {}
mod role_permissions_form {}
mod admin_html_form_text_error {}
mod admin_html_form_key_error {}
mod std_admin_html_selected_error {}
mod admin_html_form_text {}
mod admin_html_form_key {}
mod std_admin_html_selected {}
mod settings_form {}
mod admin_html_form_selected_max_items {}
