#[path = "application_roles_mutations_create.rs"]
pub(super) mod mutations_create;
#[path = "application_roles_mutations_delete.rs"]
pub(super) mod mutations_delete;
#[path = "application_roles_mutations_set_permissions.rs"]
pub(super) mod mutations_set_permissions;
#[path = "application_roles_mutations_update.rs"]
pub(super) mod mutations_update;
#[path = "application_roles_queries_list.rs"]
pub(super) mod queries_list;
#[path = "application_roles_queries_list_permissions.rs"]
pub(super) mod queries_list_permissions;
#[path = "application_roles_queries_roles_page.rs"]
pub(super) mod queries_roles_page;
