#[path = "mutations_set_ban.rs"]
pub(super) mod mutations_set_ban;
#[path = "mutations_set_password.rs"]
pub(super) mod mutations_set_password;
#[path = "mutations_set_roles.rs"]
pub(super) mod mutations_set_roles;
#[path = "queries_users_page.rs"]
pub(super) mod queries_users_page;
#[path = "user_mutations_create.rs"]
pub(super) mod user_mutations_create;
#[path = "user_mutations_delete.rs"]
pub(super) mod user_mutations_delete;
#[path = "user_mutations_update.rs"]
pub(super) mod user_mutations_update;
#[path = "user_queries_list.rs"]
pub(super) mod user_queries_list;
