[package]
authors = ["sergey shmakov <tyfaproject@gmail.com>"]
edition.workspace = true
name = "server_admin_frontend"
version.workspace = true
publish.workspace = true
description = "Reusable Rust administrative frontend"
repository.workspace = true

license.workspace = true
keywords = ["admin", "frontend"]
categories = ["web-programming"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
constants_usize = { workspace = true }
constants_u32 = { workspace = true }
frontend_contract = { workspace = true }
optimal_memory_layout = { workspace = true }
newtype = { workspace = true }
server_admin_contract = { workspace = true }
singlestage = { workspace = true }
constants_str = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum = { workspace = true }
leptos = { workspace = true, features = ["ssr"] }
to_err_string = { workspace = true }
tower-http = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
leptos = { workspace = true, features = ["csr"] }
serde = { workspace = true }
serde_json = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true, features = [
  "Document",
  "Element",
  "Headers",
  "HtmlDocument",
  "HtmlElement",
  "Location",
  "Request",
  "RequestInit",
  "Response",
  "UrlSearchParams",
  "Window",
] }

[dev-dependencies]
constants_i64 = { workspace = true }
constants_u64 = { workspace = true }

[lints]
workspace = true
