[package]
name = "generate_pg_types_test"
version = "0.1.0"
publish = false
description = "Rust microservice workspace component"
repository = "https://github.com/kuqmua/rust_workspace_template"

license = "MIT"
edition = "2024"

[dev-dependencies]
str_constants = { workspace = true }
quote = { workspace = true }
frontend_contract = { workspace = true }
macro_clippy_check_common = { workspace = true, features = ["test-utils"] }
generate_pg_types_src = { workspace = true }
macros_helpers = { workspace = true, features = ["test-utils"] }
chrono = { workspace = true }
pg_types_chrono_net = { workspace = true }
pg_types_numeric = { workspace = true }
pg_types_text_misc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
utoipa = { workspace = true }
[lints]
workspace = true

[features]
test-utils = ["macro_clippy_check_common/test-utils"]
