[package]
name = "git_info"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true


[dependencies]
generate_accessor = { workspace = true }
constants_str = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
newtype = { workspace = true }
optimal_memory_layout = { workspace = true }

[dev-dependencies]
constants_usize = { workspace = true }

[lints]
workspace = true
