[package]
name = "git_info"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true


[dependencies]
proc_macro_newtype_from_inner = { workspace = true }
proc_macro_newtype_into_inner_from = { workspace = true }
proc_macro_newtype_as_ref_inner = { workspace = true }
proc_macro_getters = { workspace = true }
constants_str = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
proc_macro_newtype_as_ref_owned = { workspace = true }
proc_macro_newtype_as_ref_str = { workspace = true }
proc_macro_newtype_deref_inner = { workspace = true }
proc_macro_newtype_deref_mut_inner = { workspace = true }
proc_macro_newtype_display = { workspace = true }
proc_macro_newtype_not_inner = { workspace = true }
proc_macro_newtype_partial_eq_inner = { workspace = true }
proc_macro_newtype_try_from = { workspace = true }
proc_macro_optimal_memory_layout = { workspace = true }

[dev-dependencies]
constants_usize = { workspace = true }

[lints]
workspace = true
