[package]
name = "git_info"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true


[dependencies]
str_constants = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
newtype = { workspace = true }
optimal_memory_layout = { workspace = true }

[dev-dependencies]
usize_constants = { workspace = true }

[lints]
workspace = true
