proc_macro_naming_generate_self_upper_camel_case_and_snake_case_str_and_token_stream::generate_self_upper_camel_case_and_snake_case_str_and_token_stream!(
    [
        ["self", "payload"],
        ["try", "self"],
        ["self", "error", "with", "serde"],
        ["self", "payload", "example"],
        ["self", "create"],
        ["self", "read"],
        ["self", "read", "inner"],
        ["self", "update"],
        ["self", "update", "for", "query"],
        ["self", "select"],
        ["self", "with", "serde"],
        ["self", "try", "from", "env", "error"],
        ["get", "self"],
        ["try", "from", "std", "env", "var", "ok", "self", "error"],
        ["error", "self"],
        ["is", "self", "update", "exist"],
        ["self", "where"],
        ["std", "optional", "optional", "self"],
        ["self", "update", "element"],
        ["self", "update", "try", "new", "error"],
        ["std", "optional", "optional", "self", "where"],
        ["self", "non", "null"],
        ["pg", "type", "where", "self"],
        ["self", "table", "type"],
        ["self", "origin"],
        ["self", "select", "element"],
        ["self", "read", "try", "from", "error"],
        ["element", "self"],
        ["self", "prep", "pg", "error"],
        ["self", "where", "many"],
        ["self", "where", "many", "try", "new", "error"],
        ["std", "optional", "optional", "self", "where", "many"],
        [
            "try", "from", "sqlx", "pg", "pg", "row", "with", "not", "empty", "unique", "vec",
            "self", "select"
        ],
        ["update", "query", "part", "self"],
        ["self", "tests"],
        ["self", "origin", "try", "new", "error"],
        ["self", "origin", "try", "new", "for", "de", "error"],
        ["self", "read", "ids"],
        ["self", "read", "ids", "h"],
        ["self", "last"],
        ["self", "current"],
        ["self", "create", "for", "query"],
        ["self", "update", "for", "query", "element"],
        ["self", "dm", "parameters"],
        ["self", "dm", "payload"],
        ["self", "dlo", "parameters"],
        ["self", "dlo", "payload"],
        ["self", "try", "ro", "error"],
        ["self", "ro", "error", "with", "serde"],
        ["self", "um", "parameters"],
        ["self", "um", "payload"],
        ["self", "try", "dlo", "error"],
        ["self", "dlo", "error", "with", "serde"],
        ["self", "h"],
        ["try", "self", "h"],
        ["d", "self"],
        ["d", "self", "if"],
        [
            "self",
            "read",
            "ids",
            "to2",
            "dimensions",
            "vec",
            "read",
            "inner",
            "accumulator"
        ],
        ["self", "generate", "pg", "table", "mod"]
    ]
);
