[package]
name = "pg_types_common"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dependencies]
str_constants = { workspace = true }
serde = { workspace = true }
utoipa = { workspace = true }
thiserror = { workspace = true }
schemars = { workspace = true }
pg_crud_common = { workspace = true, features = ["test-utils"] }
location_lib = { workspace = true }
location_macros = { workspace = true }
location = { workspace = true }
optml = { workspace = true }
newtype = { workspace = true }
to_err_string = { workspace = true }
[lints]
workspace = true
