[package]
name = "pg_types"
version = "0.1.0"
publish = false
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]
edition = "2024"

[dependencies]
pg_types_cmn = { workspace = true }
pg_types_numeric = { workspace = true }
pg_types_chrono_net = { workspace = true }
pg_types_text_misc = { workspace = true }
[lints]
workspace = true

[features]
test-utils = [
    "pg_types_numeric/test-utils",
    "pg_types_chrono_net/test-utils",
    "pg_types_text_misc/test-utils",
]