[package]
name = "file_storage"
version.workspace = true
publish.workspace = true
description = "Symlink-resistant staged file storage"
repository.workspace = true

license.workspace = true
keywords = ["file", "storage"]
categories = ["filesystem"]
edition.workspace = true

[dependencies]
generate_accessor = { workspace = true }
generate_constructor = { workspace = true }
constants_usize = { workspace = true }
constants_u64 = { workspace = true }
optimal_memory_layout = { workspace = true }
bounded_types = { workspace = true }
newtype = { workspace = true }
constants_str = { workspace = true }
text_policy = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
