#![allow(
    clippy::arbitrary_source_item_ordering,
    clippy::wildcard_imports,
    reason = "root-owned token emitters share the compatibility facade vocabulary"
)]

pub mod common_d_token_stream_builder;
pub mod de_len;
pub mod default_some_one_or_default_some_one_with_max_page_size;
pub mod derive_or_impl;
pub mod dimension;
pub mod dimension_index_number;
pub mod dimension_number;
pub mod emission_types;
pub mod eq_operator_variant;
pub mod eq_or_eq_using_fields;
pub mod error_enum_d_token_stream_builder;
pub mod generate_de_double_quoted_token_stream;
pub mod generate_dimension_number_pagination_token_stream;
pub mod generate_explicit_value_declaration_token_stream;
pub mod generate_explicit_value_initialization_token_stream;
pub mod generate_if_let_some_match_ok_assign_query_or_return_err_token_stream;
pub mod generate_impl_all_variants_default_some_one_element_max_page_size_token_stream;
pub mod generate_impl_all_variants_default_some_one_element_token_stream;
pub mod generate_impl_crate_is_string_empty_for_identifier_token_stream;
pub mod generate_impl_de_for_struct_by_fields_token_stream;
pub mod generate_impl_de_for_struct_token_stream;
pub mod generate_impl_default_some_one_element_max_page_size_token_stream;
pub mod generate_impl_default_some_one_element_token_stream;
pub mod generate_impl_display_and_to_err_string_debug_token_stream;
pub mod generate_impl_pg_crud_all_variants_default_some_one_element_max_page_size_token_stream;
pub mod generate_impl_pg_crud_all_variants_default_some_one_element_token_stream;
pub mod generate_impl_pg_crud_common_all_variants_default_some_one_element_token_stream;
pub mod generate_impl_pg_crud_common_default_some_one_element_max_page_size_token_stream;
pub mod generate_impl_pg_crud_common_default_some_one_element_token_stream;
pub mod generate_impl_pg_crud_default_some_one_element_max_page_size_token_stream;
pub mod generate_impl_pg_crud_default_some_one_element_token_stream;
pub mod generate_impl_pg_type_not_primary_key_for_identifier_token_stream;
pub mod generate_impl_pg_type_test_cases_for_identifier_token_stream;
pub mod generate_impl_pg_type_token_stream;
pub mod generate_impl_sqlx_decode_sqlx_pg_for_identifier_token_stream;
pub mod generate_impl_sqlx_encode_sqlx_pg_for_identifier_token_stream;
pub mod generate_impl_sqlx_type_and_encode_for_identifier_token_stream;
pub mod generate_impl_sqlx_type_for_identifier_token_stream;
pub mod generate_impl_to_err_string_no_generics_token_stream;
pub mod generate_match_not_empty_unique_vec_try_new_some_or_none_token_stream;
pub mod generate_match_ok_assign_or_return_err_token_stream;
pub mod generate_match_ok_or_return_err_token_stream;
pub mod generate_match_try_new_in_de_token_stream;
pub mod generate_mod_with_pub_use_token_stream;
pub mod generate_optional_type_declaration_token_stream;
pub mod generate_pg_type_where_token_stream;
pub mod generate_query_part_error_write_into_buffer_token_stream;
pub mod generate_read_ids_and_create_into_vec_where_eq_using_fields_token_stream;
pub mod generate_read_ids_and_create_into_where_eq_token_stream;
pub mod generate_read_inner_into_read_or_update_with_new_or_try_new_unwraped_token_stream;
pub mod generate_return_err_query_part_error_write_into_buffer_token_stream;
pub mod generate_sqlx_types_json_type_declaration_token_stream;
pub mod generate_struct_identifier_double_quoted_token_stream;
pub mod generate_struct_identifier_with_number_elements_double_quoted_token_stream;
pub mod generate_vec_tokens_declaration_token_stream;
pub mod impl_pg_type_eq_operator_for_identifier_token_stream;
pub mod impl_pg_type_where_filter_for_identifier_token_stream;
pub mod import;
pub mod import_path_str;
pub mod import_snake_case_str;
pub mod is_nl_prefix_str_max_len;
pub mod is_nullable;
pub mod is_nullable_prefix_str;
pub mod is_standard_non_null;
pub mod maybe_wrap_into_braces_token_stream;
pub mod names_context;
pub mod non_null_or_nullable_str;
pub mod panic_uuid_ref;
pub mod parse_error_id_ref;
pub mod parse_strs_to_ts2_vec;
pub mod parse_token_stream_strings;
pub mod pg_crud_common_query_part_error_checked_add_initialization_token_stream;
pub mod pg_crud_common_query_part_error_token_stream;
pub mod pg_filter;
pub mod pg_type_filter;
pub mod proc_macro2_generated_rust_token_stream_vec;
pub mod read_or_update;
pub mod serde_error_enum_d_token_stream_builder;
pub mod struct_elements_length;
pub mod syn_field_refs;
pub mod syn_identifier_type_refs;
#[cfg(test)]
pub mod test_domain_types_token_emission_tests;
#[cfg(test)]
pub mod test_tests_domain_types;
pub mod wrap_into_braces;
pub mod wrap_into_scopes_token_stream;

const _: fn(&str) -> Result<(), bounded_types::bounded_string_error::BoundedStringError> =
    bounded_types::bounded_string::BoundedString::<0, 0>::validate_str;
