[package]
name = "gen_pg_tbl_test_cnt"
publish = false
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]
[lints]
workspace = true
[dependencies]
axum = { workspace = true }
http = { workspace = true }
sqlx = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
utoipa = { workspace = true }
git_info = { workspace = true }
loc_lib = { workspace = true }
pg_crud = { workspace = true, features = ["test-utils"] }
optml = { workspace = true }