[package]
name = "naming"
version = "0.1.0"
publish = false
description = "Rust microservice workspace component"
repository = "https://github.com/kuqmua/rust_workspace_template"

license = "MIT"
edition = "2024"

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
generate_quotes = { workspace = true }
naming_macros = { workspace = true }
naming_common = { workspace = true }
newtype = { workspace = true }
optml = { workspace = true }
[lints]
workspace = true
