#[test]
fn test_data_grid() {
    let columns = server_admin_contract::admin_data_columns::AdminDataColumns::try_from(vec![
        server_admin_contract::admin_data_column::AdminDataColumn::new(
            server_admin_contract::admin_data_filters::AdminDataFilters::try_from(Vec::new())
                .expect(constants_str::VALUE_D0BD1ECC),
            frontend_contract::input_kind::InputKind::Number,
            server_admin_contract::admin_text::AdminText::try_from(String::from(
                constants_str::VALUE_1D438D9B,
            ))
            .expect(constants_str::VALUE_46CE1BB0),
            server_admin_contract::admin_text::AdminText::try_from(String::from(
                constants_str::SQL_NAMES_ID,
            ))
            .expect(constants_str::VALUE_81310A83),
        ),
        server_admin_contract::admin_data_column::AdminDataColumn::new(
            server_admin_contract::admin_data_filters::AdminDataFilters::try_from(vec![
                server_admin_contract::admin_data_filter::AdminDataFilter::from(
                    frontend_contract::filter_operation::FilterOperation::Eq,
                ),
                server_admin_contract::admin_data_filter::AdminDataFilter::from(
                    frontend_contract::filter_operation::FilterOperation::Regex,
                ),
                server_admin_contract::admin_data_filter::AdminDataFilter::from(
                    frontend_contract::filter_operation::FilterOperation::Between,
                ),
            ])
            .expect(constants_str::VALUE_4C7734E6),
            frontend_contract::input_kind::InputKind::Text,
            server_admin_contract::admin_text::AdminText::try_from(String::from(
                constants_str::VALUE_B2D6201D,
            ))
            .expect(constants_str::VALUE_EC14A0FD),
            server_admin_contract::admin_text::AdminText::try_from(String::from(
                constants_str::LOGIN,
            ))
            .expect(constants_str::VALUE_6A1237E9),
        ),
    ])
    .expect(constants_str::DIAGNOSTIC_57462AD9);
    let values = server_admin_contract::admin_texts::AdminTexts::try_from(vec![
        server_admin_contract::admin_text::AdminText::try_from(String::from(
            constants_str::VALUE_42,
        ))
        .expect(constants_str::VALUE_1DF3FF47),
        server_admin_contract::admin_text::AdminText::try_from(String::from(
            constants_str::VALUE_2BD806C9,
        ))
        .expect(constants_str::VALUE_BED65ED1),
    ])
    .expect(constants_str::DIAGNOSTIC_58FED1D1);
    let rows = server_admin_contract::admin_data_rows::AdminDataRows::try_from(vec![
        server_admin_contract::admin_data_row::AdminDataRow::new(values),
    ])
    .expect(constants_str::DIAGNOSTIC_AC944CCC);
    let view = server_admin_contract::admin_data_table_view::AdminDataTableView::new(
        columns.clone(),
        rows.clone(),
        server_admin_contract::admin_data_table::AdminDataTable::Users,
        server_admin_contract::admin_page_total::AdminPageTotal::from(1u64),
    );
    let filter_view = server_admin_contract::admin_data_table_view::AdminDataTableView::new(
        columns,
        rows,
        server_admin_contract::admin_data_table::AdminDataTable::RolePermissions,
        server_admin_contract::admin_page_total::AdminPageTotal::from(1u64),
    );

    let default_query =
        server_admin_contract::admin_data_table_query::AdminDataTableQuery::default();
    let html = crate::admin_ssr_view_ext_tests::AdminSsrViewExt::render_admin_ssr(
        crate::data_table_grid::data_table_grid(&view, &default_query),
    );

    assert!(html.as_ref().contains(constants_str::VALUE_469219C9));
    assert!(html.as_ref().contains(constants_str::VALUE_846B8D6B));
    assert!(html.as_ref().contains(constants_str::VALUE_31819FEE));
    assert!(html.as_ref().contains(constants_str::VALUE_8886AF1E));
    assert!(html.as_ref().contains(constants_str::VALUE_38C2F107));
    assert!(html.as_ref().contains(constants_str::VALUE_447968F6));
    assert!(html.as_ref().contains(constants_str::VALUE_0702D49A));
    assert!(html.as_ref().contains(constants_str::VALUE_7CA6DA11));
    assert!(html.as_ref().contains(constants_str::VALUE_0F228174));
    assert!(
        html.as_ref()
            .contains(constants_str::ADMIN_UI_EXPECT_VALUE_50E5C8E7)
    );
    assert!(html.as_ref().contains(constants_str::VALUE_80DFAFAE));
    assert!(html.as_ref().contains(constants_str::VALUE_ED7335DF));
    assert!(!html.as_ref().contains(constants_str::VALUE_B2F8E281));

    let query = server_admin_contract::admin_data_table_query::AdminDataTableQuery::new(
        server_admin_contract::admin_data_table_filter_query::AdminDataTableFilterQuery::new(
            Some(
                server_admin_contract::admin_filter_field::AdminFilterField::try_from(
                    String::from(constants_str::LOGIN),
                )
                .expect(constants_str::DIAGNOSTIC_774BC583),
            ),
            Some(frontend_contract::filter_operation::FilterOperation::Eq),
            Some(
                server_admin_contract::admin_filter_value::AdminFilterValue::try_from(
                    String::from(constants_str::VALUE_2BD806C9),
                )
                .expect(constants_str::DIAGNOSTIC_63D17F8E),
            ),
            None,
        ),
        server_admin_contract::admin_table_query::AdminTableQuery::default(),
    );
    let filters_html = crate::admin_ssr_view_ext_tests::AdminSsrViewExt::render_admin_ssr(
        crate::data_table_grid::data_table_grid(&filter_view, &query),
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::VALUE_B67A1896)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::VALUE_B2F8E281)
    );
    assert!(
        !filters_html
            .as_ref()
            .contains(constants_str::VALUE_A01DB716)
    );
    let (_before_login, login_tail) = filters_html
        .as_ref()
        .split_once(constants_str::VALUE_3837854C)
        .expect(constants_str::DIAGNOSTIC_45B73477);
    let (login_header, _after_login) = login_tail
        .split_once(constants_str::VALUE_25C350AC)
        .expect(constants_str::DIAGNOSTIC_E8120A92);
    assert!(login_header.contains(constants_str::VALUE_B2F8E281));
    assert!(login_header.contains(constants_str::VALUE_EDC93DB7));
    assert!(login_header.contains(constants_str::VALUE_68BB5D51));
    assert!(login_header.contains(constants_str::VALUE_802A0142));
    let (_before_id, id_tail) = filters_html
        .as_ref()
        .split_once(constants_str::VALUE_469219C9)
        .expect(constants_str::DIAGNOSTIC_C8A92EF4);
    let (id_header, _after_id) = id_tail
        .split_once(constants_str::VALUE_25C350AC)
        .expect(constants_str::DIAGNOSTIC_58CDF783);
    assert!(!id_header.contains(constants_str::VALUE_B2F8E281));
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::ADMIN_UI_EXPECT_VALUE_1665AC0E)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::VALUE_96BBC0EC)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::ADMIN_UI_EXPECT_VALUE_D641BA27)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::ADMIN_UI_EXPECT_VALUE_6FB367C6)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::VALUE_1C61CF88)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::VALUE_E7A7CF18)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::VALUE_5CAEF150)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::VALUE_AC56ED1F)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::VALUE_C7C36CF4)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::VALUE_D241380B)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::VALUE_26B901BB)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::VALUE_022ECEBF)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::VALUE_DDF681C4)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::ADMIN_UI_EXPECT_VALUE_FF2F6A65)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::VALUE_FEA2007C)
    );
    assert!(
        !filters_html
            .as_ref()
            .contains(constants_str::ADMIN_UI_EXPECT_VALUE_D8E97E9A)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::ADMIN_UI_EXPECT_VALUE_8C4051D1)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::ADMIN_UI_EXPECT_VALUE_69FA33B8)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::ADMIN_UI_EXPECT_VALUE_E1FD30CF)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::VALUE_F37D548A)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::ADMIN_UI_EXPECT_VALUE_F969D2DE)
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::ADMIN_UI_EXPECT_VALUE_BD7A6256)
    );
    let apply_position = filters_html
        .as_ref()
        .find(constants_str::ADMIN_UI_EXPECT_VALUE_38228244)
        .expect(constants_str::DIAGNOSTIC_10C26D45);
    let close_position = filters_html
        .as_ref()
        .find(constants_str::ADMIN_UI_EXPECT_VALUE_0D4379EB)
        .expect(constants_str::DIAGNOSTIC_1542A5C3);
    let clear_position = filters_html
        .as_ref()
        .find(constants_str::ADMIN_UI_EXPECT_VALUE_BD7A6256)
        .expect(constants_str::DIAGNOSTIC_58F35E11);
    assert!(close_position > apply_position);
    assert!(clear_position > apply_position);
    assert!(clear_position > close_position);
    assert_eq!(
        filters_html
            .as_ref()
            .matches(constants_str::VALUE_AC55DE88)
            .count(),
        constants_usize::ONE
    );
    assert_eq!(
        filters_html
            .as_ref()
            .matches(constants_str::ADMIN_UI_EXPECT_VALUE_38228244)
            .count(),
        constants_usize::ONE
    );
    assert!(
        filters_html
            .as_ref()
            .contains(constants_str::VALUE_FDB71479)
    );
    assert!(
        !filters_html
            .as_ref()
            .contains(constants_str::VALUE_155A24DE)
    );
    assert!(
        !filters_html
            .as_ref()
            .contains(constants_str::VALUE_5EBA168E)
    );
    assert_eq!(
        filters_html
            .as_ref()
            .matches(constants_str::VALUE_939560A4)
            .count(),
        constants_usize::ONE
    );

    let admin = crate::domain_types_ssr_tests::test_admin();
    let branding = crate::domain_types_ssr_tests::test_branding();
    let page_html = crate::render_data_tables::render_data_tables(
        Some(&filter_view),
        &query,
        &admin,
        &branding,
    );
    assert!(page_html.as_ref().contains(constants_str::VALUE_3837854C));
    assert!(page_html.as_ref().contains(constants_str::VALUE_AC55DE88));
    let empty_html = crate::render_data_tables::render_data_tables(None, &query, &admin, &branding);
    assert!(!empty_html.as_ref().contains(constants_str::VALUE_BBB98D48));
    assert!(
        empty_html
            .as_ref()
            .contains(server_admin_contract::admin_html_action::AdminHtmlAction::SignOut.get())
    );
}
