[package]
name = "pg_types_chrono_net"
version = "0.1.0"
publish = false
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]
edition = "2024"

[dependencies]
sqlx = { workspace = true }
serde = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
gen_pg_types = { workspace = true }
pg_crud_cmn = { workspace = true }
loc_lib = { workspace = true }
wh_flts = { workspace = true }
optml = { workspace = true }
[lints]
workspace = true

[features]
test-utils = ["pg_crud_cmn/test-utils"]
