[package]
name = "server_app_state_macros"
version = "0.1.0"
publish = false
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]
edition = "2024"
[lib]
proc-macro = true
[dependencies]
quote = { workspace = true }
workspace_macro_helpers = { workspace = true }
[lints]
workspace = true
