[package]
edition.workspace = true
name = "location"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true

[lib]
proc-macro = true

[dependencies]
constants_str = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
macro_helpers = { workspace = true }
generate_quotes = { workspace = true }
panic_location = { workspace = true }
token_patterns = { workspace = true }
naming = { workspace = true }
optimal_memory_layout = { workspace = true }
newtype = { workspace = true }
[lints]
workspace = true
