[package]
name = "to_err_string"
version = "0.1.0"
publish = false
description = "Rust microservice workspace component"
repository = "https://github.com/kuqmua/rust_workspace_template"

license = "MIT"
edition = "2024"


[dependencies]
str_constants = { workspace = true }
tracing = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
to_err_string_macros = { workspace = true }
newtype = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum = { workspace = true }
http = { workspace = true }
http-body = { workspace = true }
reqwest = { workspace = true }
sqlx = { workspace = true }
time = { workspace = true }

[lints]
workspace = true
