[package]
name = "notification_service"
version = "0.1.0"
publish = false
description = "Independently deployable notification microservice reference implementation"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["notification", "microservice"]
categories = ["web-programming"]
edition = "2024"

[[bin]]
name = "notification_service"
path = "src/main.rs"

[dependencies]
app_state = { workspace = true }
axum = { workspace = true }
http = { workspace = true }
notification_service_config = { workspace = true }
notification_service_contract = { workspace = true }
secrecy = { workspace = true }
server_runtime = { workspace = true }
sqlx = { workspace = true, features = ["macros"] }
str_constants = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
