[package]
name = "token_patterns"
version = "0.1.0"
publish = false
description = "Rust microservice workspace component"
repository = "https://github.com/kuqmua/rust_workspace_template"

license = "MIT"
edition = "2024"

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
optml = { workspace = true }
token_patterns_macros = { workspace = true }
[lints]
workspace = true
