[package]
edition = "2024"
name = "gen_pg_tbl"
version = "0.1.0"
publish = false
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[lib]
proc-macro = true

[dependencies]
gen_pg_tbl_src = { workspace = true }
macros_helpers = { workspace = true }
[lints]
workspace = true
