[package]
name = "initialize_environment_files"
version = "0.1.0"
publish = false
description = "Safely initialize workspace environment files from examples"
repository = "https://github.com/kuqmua/rust_workspace_template"

license = "MIT"
keywords = ["environment"]
categories = ["development-tools"]
edition = "2024"

[dependencies]
str_constants = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
uuid = { workspace = true }

[lints]
workspace = true
