[package]
name = "generate_where_filters"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true


[lib]
proc-macro = true

[dependencies]
constants_str = { workspace = true }
generate_where_filters_src = { workspace = true }
[lints]
workspace = true
