[package]
name = "naming_macros"
version = "0.1.0"
publish = false
description = "Rust microservice workspace component"
repository = "https://github.com/kuqmua/rust_workspace_template"

license = "MIT"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
str_constants = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
generate_quotes = { workspace = true }
panic_location = { workspace = true }
token_patterns = { workspace = true }
naming_common = { workspace = true }
newtype = { workspace = true }
[lints]
workspace = true
