[package]
edition.workspace = true
name = "macro_helpers"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true

[dependencies]
proc_macro_newtype_from_inner = { workspace = true }
proc_macro_newtype_to_tokens = { workspace = true }
proc_macro_newtype_into_inner_from = { workspace = true }
proc_macro_newtype_as_ref_inner = { workspace = true }
bounded_types = { workspace = true }
constants_usize = { workspace = true }
constants_u8 = { workspace = true }
atomic-write-file = { workspace = true }
constants_str = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
strum_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
server_runtime_http = { workspace = true }
thiserror = { workspace = true }
token_patterns = { workspace = true }
generate_quotes = { workspace = true }
proc_macro_getters = { workspace = true }
proc_macro_new = { workspace = true }
naming = { workspace = true }
naming_common = { workspace = true }
proc_macro_naming_as_ref_str_enum_with_unit_fields_to_upper_camel_case_str = { workspace = true }
proc_macro_naming_as_ref_str_enum_with_unit_fields_to_snake_case_str = { workspace = true }
proc_macro_naming_enum_with_unit_fields_to_snake_case_str = { workspace = true }
proc_macro_naming_enum_with_unit_fields_to_upper_camel_case_str = { workspace = true }
proc_macro_naming_enum_with_unit_fields_to_upper_snake_case_str = { workspace = true }
proc_macro_newtype_as_ref_owned = { workspace = true }
proc_macro_newtype_as_ref_str = { workspace = true }
proc_macro_newtype_as_ref_target = { workspace = true }
proc_macro_newtype_deref_inner = { workspace = true }
proc_macro_newtype_deref_mut_inner = { workspace = true }
proc_macro_newtype_deref_target = { workspace = true }
proc_macro_newtype_display = { workspace = true }
proc_macro_newtype_not_inner = { workspace = true }
proc_macro_newtype_bounded_string_wrapper = { workspace = true }
proc_macro_generate_derive_token_stream_builder = { workspace = true }
proc_macro_optimal_memory_layout = { workspace = true }

[dev-dependencies]
constants_u32 = { workspace = true }

[features]
test-utils = ["dep:serde_json"]
[lints]
workspace = true
