#[derive(
    proc_macro_optimal_memory_layout::OptimalMemoryLayout,
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    proc_macro_newtype_wire_enum::WireEnum,
    utoipa::ToSchema,
)]
#[wire_enum(
    ref_type = crate::admin_rule_str_ref::AdminRuleStrRef,
    error_message = constants_str::UNKNOWN_ADMINISTRATOR_RULE,
)]
pub enum AdminRule {
    #[wire("access_sessions:delete")]
    AccessSessionsDelete,
    #[wire("access_sessions:read")]
    AccessSessionsRead,
    #[wire("audit_log:read")]
    AuditLogRead,
    #[wire("cleanup_status:read")]
    CleanupStatusRead,
    #[wire("login_attempts:read")]
    LoginAttemptsRead,
    #[wire("metrics:read")]
    MetricsRead,
    #[wire("openapi:read")]
    OpenApiRead,
    #[wire("permission_actions:read")]
    PermissionActionsRead,
    #[wire("permission_resource_actions:read")]
    PermissionResourceActionsRead,
    #[wire("permission_resources:read")]
    PermissionResourcesRead,
    #[wire("rules:read")]
    RulesRead,
    #[wire("rate_limits:read")]
    RateLimitsRead,
    #[wire("refresh_tokens:read")]
    RefreshTokensRead,
    #[wire("role_rules:create")]
    RoleRulesCreate,
    #[wire("role_rules:delete")]
    RoleRulesDelete,
    #[wire("role_rules:read")]
    RoleRulesRead,
    #[wire("role_rules:update")]
    RoleRulesUpdate,
    #[wire("roles:create")]
    RolesCreate,
    #[wire("roles:delete")]
    RolesDelete,
    #[wire("roles:read")]
    RolesRead,
    #[wire("roles:update")]
    RolesUpdate,
    #[wire("system_settings:read")]
    SystemSettingsRead,
    #[wire("system_settings:update")]
    SystemSettingsUpdate,
    #[wire("tables:read")]
    TablesRead,
    #[wire("user_roles:create")]
    UserRolesCreate,
    #[wire("user_roles:delete")]
    UserRolesDelete,
    #[wire("user_roles:read")]
    UserRolesRead,
    #[wire("user_roles:update")]
    UserRolesUpdate,
    #[wire("users:create")]
    UsersCreate,
    #[wire("users:delete")]
    UsersDelete,
    #[wire("users:read")]
    UsersRead,
    #[wire("users:update")]
    UsersUpdate,
}
