#![allow(
    unused_imports,
    clippy::arbitrary_source_item_ordering,
    clippy::wildcard_imports,
    reason = "root-owned modules retain the vocabulary and DTO/route-metadata grouping previously inherited from the contract owner module"
)]

mod admin_api_body_max_bytes;
pub(crate) use crate::admin_api_body_max_bytes::*;
mod admin_api_route_path;
pub(crate) use crate::admin_api_route_path::*;
mod admin_audit_cursor;
pub(crate) use crate::admin_audit_cursor::*;
mod admin_audit_details_bytes;
pub(crate) use crate::admin_audit_details_bytes::*;
mod admin_audit_details_max_bytes;
pub(crate) use crate::admin_audit_details_max_bytes::*;
mod admin_audit_details_too_large;
pub(crate) use crate::admin_audit_details_too_large::*;
mod admin_audit_export;
pub(crate) use crate::admin_audit_export::*;
mod admin_audit_export_csv;
pub(crate) use crate::admin_audit_export_csv::*;
mod admin_audit_export_route;
pub(crate) use crate::admin_audit_export_route::*;
mod admin_audit_log_id;
pub(crate) use crate::admin_audit_log_id::*;
mod admin_audit_log_route;
pub(crate) use crate::admin_audit_log_route::*;
mod admin_audit_page;
pub(crate) use crate::admin_audit_page::*;
mod admin_audit_timestamp;
pub(crate) use crate::admin_audit_timestamp::*;
mod admin_audit_view;
pub(crate) use crate::admin_audit_view::*;
mod admin_audit_views;
pub(crate) use crate::admin_audit_views::*;
mod admin_bool;
pub(crate) use crate::admin_bool::*;
mod admin_bounded_vec;
pub(crate) use crate::admin_bounded_vec::*;
mod admin_branding_route;
pub(crate) use crate::admin_branding_route::*;
mod admin_branding_view;
pub(crate) use crate::admin_branding_view::*;
mod admin_change_own_password_req;
pub(crate) use crate::admin_change_own_password_req::*;
mod admin_change_own_password_route;
pub(crate) use crate::admin_change_own_password_route::*;
mod admin_collection_error;
pub(crate) use crate::admin_collection_error::*;
mod admin_collection_max_items;
pub(crate) use crate::admin_collection_max_items::*;
mod admin_create_role_req;
pub(crate) use crate::admin_create_role_req::*;
mod admin_create_role_res;
pub(crate) use crate::admin_create_role_res::*;
mod admin_create_role_route;
pub(crate) use crate::admin_create_role_route::*;
mod admin_create_user_req;
pub(crate) use crate::admin_create_user_req::*;
mod admin_create_user_res;
pub(crate) use crate::admin_create_user_res::*;
mod admin_create_user_route;
pub(crate) use crate::admin_create_user_route::*;
mod admin_data_column;
pub(crate) use crate::admin_data_column::*;
mod admin_data_columns;
pub(crate) use crate::admin_data_columns::*;
mod admin_data_columns_csv_ref;
pub(crate) use crate::admin_data_columns_csv_ref::*;
mod admin_data_filter;
pub(crate) use crate::admin_data_filter::*;
mod admin_data_filters;
pub(crate) use crate::admin_data_filters::*;
mod admin_data_order_ref;
pub(crate) use crate::admin_data_order_ref::*;
mod admin_data_row;
pub(crate) use crate::admin_data_row::*;
mod admin_data_rows;
pub(crate) use crate::admin_data_rows::*;
mod admin_data_table;
pub(crate) use crate::admin_data_table::*;
mod admin_data_table_catalog;
pub(crate) use crate::admin_data_table_catalog::*;
mod admin_data_table_filter_query;
pub(crate) use crate::admin_data_table_filter_query::*;
mod admin_data_table_frontend_path;
pub(crate) use crate::admin_data_table_frontend_path::*;
mod admin_data_table_query;
pub(crate) use crate::admin_data_table_query::*;
mod admin_data_table_route;
pub(crate) use crate::admin_data_table_route::*;
mod admin_data_table_spec;
pub(crate) use crate::admin_data_table_spec::*;
mod admin_data_table_str_ref;
pub(crate) use crate::admin_data_table_str_ref::*;
mod admin_data_table_view;
pub(crate) use crate::admin_data_table_view::*;
mod admin_data_tables;
pub(crate) use crate::admin_data_tables::*;
mod admin_data_tables_route;
pub(crate) use crate::admin_data_tables_route::*;
mod admin_default_page_limit;
pub(crate) use crate::admin_default_page_limit::*;
mod admin_default_route;
pub(crate) use crate::admin_default_route::*;
mod admin_delete_role_route;
pub(crate) use crate::admin_delete_role_route::*;
mod admin_delete_user_route;
pub(crate) use crate::admin_delete_user_route::*;
mod admin_display_name;
pub(crate) use crate::admin_display_name::*;
mod admin_empty_collection;
pub(crate) use crate::admin_empty_collection::*;
mod admin_filter_field;
pub(crate) use crate::admin_filter_field::*;
mod admin_filter_operation_key;
pub(crate) use crate::admin_filter_operation_key::*;
mod admin_filter_value;
pub(crate) use crate::admin_filter_value::*;
mod admin_frontend_path;
pub(crate) use crate::admin_frontend_path::*;
mod admin_html_action;
pub(crate) use crate::admin_html_action::*;
mod admin_id_try_from_i64_error;
pub(crate) use crate::admin_id_try_from_i64_error::*;
mod admin_list_permissions_route;
pub(crate) use crate::admin_list_permissions_route::*;
mod admin_list_roles_route;
pub(crate) use crate::admin_list_roles_route::*;
mod admin_list_users_route;
pub(crate) use crate::admin_list_users_route::*;
mod admin_login;
pub(crate) use crate::admin_login::*;
mod admin_main_logo;
pub(crate) use crate::admin_main_logo::*;
mod admin_me_route;
pub(crate) use crate::admin_me_route::*;
mod admin_new_password;
pub(crate) use crate::admin_new_password::*;
mod admin_no_body;
pub(crate) use crate::admin_no_body::*;
mod admin_open_api_vec;
pub(crate) use crate::admin_open_api_vec::*;
mod admin_open_api_vec_phantom_data;
pub(crate) use crate::admin_open_api_vec_phantom_data::*;
mod admin_optional_setting;
pub(crate) use crate::admin_optional_setting::*;
mod admin_optional_settings;
pub(crate) use crate::admin_optional_settings::*;
mod admin_organization_contacts;
pub(crate) use crate::admin_organization_contacts::*;
mod admin_organization_name;
pub(crate) use crate::admin_organization_name::*;
mod admin_page;
pub(crate) use crate::admin_page::*;
mod admin_page_capability;
pub(crate) use crate::admin_page_capability::*;
mod admin_page_client_mode;
pub(crate) use crate::admin_page_client_mode::*;
mod admin_page_limit;
pub(crate) use crate::admin_page_limit::*;
mod admin_page_limit_error;
pub(crate) use crate::admin_page_limit_error::*;
mod admin_page_limit_visitor;
pub(crate) use crate::admin_page_limit_visitor::*;
mod admin_page_metadata;
pub(crate) use crate::admin_page_metadata::*;
mod admin_page_navigation;
pub(crate) use crate::admin_page_navigation::*;
mod admin_page_offset;
pub(crate) use crate::admin_page_offset::*;
mod admin_page_offset_visitor;
pub(crate) use crate::admin_page_offset_visitor::*;
mod admin_page_path_ref;
pub(crate) use crate::admin_page_path_ref::*;
mod admin_page_spec;
pub(crate) use crate::admin_page_spec::*;
mod admin_page_title;
pub(crate) use crate::admin_page_title::*;
mod admin_page_total;
pub(crate) use crate::admin_page_total::*;
mod admin_parameterized_route_path;
pub(crate) use crate::admin_parameterized_route_path::*;
mod admin_password;
pub(crate) use crate::admin_password::*;
mod admin_path_route_name;
pub(crate) use crate::admin_path_route_name::*;
mod admin_permission;
pub(crate) use crate::admin_permission::*;
mod admin_permission_id;
pub(crate) use crate::admin_permission_id::*;
mod admin_permission_ids;
pub(crate) use crate::admin_permission_ids::*;
mod admin_permission_requirement;
pub(crate) use crate::admin_permission_requirement::*;
mod admin_permission_str_ref;
pub(crate) use crate::admin_permission_str_ref::*;
mod admin_permission_summaries;
pub(crate) use crate::admin_permission_summaries::*;
mod admin_permission_summary;
pub(crate) use crate::admin_permission_summary::*;
mod admin_permission_value;
pub(crate) use crate::admin_permission_value::*;
mod admin_permission_values;
pub(crate) use crate::admin_permission_values::*;
mod admin_permissions_page;
pub(crate) use crate::admin_permissions_page::*;
mod admin_primary_color;
pub(crate) use crate::admin_primary_color::*;
mod admin_refresh_route;
pub(crate) use crate::admin_refresh_route::*;
mod admin_revoke_all_sessions_route;
pub(crate) use crate::admin_revoke_all_sessions_route::*;
mod admin_revoke_session_route;
pub(crate) use crate::admin_revoke_session_route::*;
mod admin_role_id;
pub(crate) use crate::admin_role_id::*;
mod admin_role_ids;
pub(crate) use crate::admin_role_ids::*;
mod admin_role_name;
pub(crate) use crate::admin_role_name::*;
mod admin_role_names;
pub(crate) use crate::admin_role_names::*;
mod admin_role_summaries;
pub(crate) use crate::admin_role_summaries::*;
mod admin_role_summary;
pub(crate) use crate::admin_role_summary::*;
mod admin_roles_page;
pub(crate) use crate::admin_roles_page::*;
mod admin_route;
pub(crate) use crate::admin_route::*;
mod admin_route_path;
pub(crate) use crate::admin_route_path::*;
mod admin_route_path_error;
pub(crate) use crate::admin_route_path_error::*;
mod admin_session_identifier;
pub(crate) use crate::admin_session_identifier::*;
mod admin_session_timestamp;
pub(crate) use crate::admin_session_timestamp::*;
mod admin_session_view;
pub(crate) use crate::admin_session_view::*;
mod admin_session_views;
pub(crate) use crate::admin_session_views::*;
mod admin_sessions_page;
pub(crate) use crate::admin_sessions_page::*;
mod admin_sessions_route;
pub(crate) use crate::admin_sessions_route::*;
mod admin_set_role_permissions_req;
pub(crate) use crate::admin_set_role_permissions_req::*;
mod admin_set_role_permissions_route;
pub(crate) use crate::admin_set_role_permissions_route::*;
mod admin_set_user_ban_req;
pub(crate) use crate::admin_set_user_ban_req::*;
mod admin_set_user_ban_route;
pub(crate) use crate::admin_set_user_ban_route::*;
mod admin_set_user_password_req;
pub(crate) use crate::admin_set_user_password_req::*;
mod admin_set_user_password_route;
pub(crate) use crate::admin_set_user_password_route::*;
mod admin_set_user_roles_req;
pub(crate) use crate::admin_set_user_roles_req::*;
mod admin_set_user_roles_route;
pub(crate) use crate::admin_set_user_roles_route::*;
mod admin_setting;
pub(crate) use crate::admin_setting::*;
mod admin_setting_input_kind;
pub(crate) use crate::admin_setting_input_kind::*;
mod admin_setting_label;
pub(crate) use crate::admin_setting_label::*;
mod admin_setting_name;
pub(crate) use crate::admin_setting_name::*;
mod admin_setting_optionality;
pub(crate) use crate::admin_setting_optionality::*;
mod admin_setting_spec;
pub(crate) use crate::admin_setting_spec::*;
mod admin_settings_route;
pub(crate) use crate::admin_settings_route::*;
mod admin_settings_view;
pub(crate) use crate::admin_settings_view::*;
mod admin_sign_in_req;
pub(crate) use crate::admin_sign_in_req::*;
mod admin_sign_in_res;
pub(crate) use crate::admin_sign_in_res::*;
mod admin_sign_in_route;
pub(crate) use crate::admin_sign_in_route::*;
mod admin_sign_out_route;
pub(crate) use crate::admin_sign_out_route::*;
mod admin_site_name;
pub(crate) use crate::admin_site_name::*;
mod admin_sort_direction;
pub(crate) use crate::admin_sort_direction::*;
mod admin_support_url;
pub(crate) use crate::admin_support_url::*;
mod admin_tab_title;
pub(crate) use crate::admin_tab_title::*;
mod admin_table_query;
pub(crate) use crate::admin_table_query::*;
mod admin_table_search;
pub(crate) use crate::admin_table_search::*;
mod admin_table_sort_field;
pub(crate) use crate::admin_table_sort_field::*;
mod admin_table_sort_field_try_from_key_error;
pub(crate) use crate::admin_table_sort_field_try_from_key_error::*;
mod admin_table_sort_key;
pub(crate) use crate::admin_table_sort_key::*;
mod admin_table_sort_key_ref;
pub(crate) use crate::admin_table_sort_key_ref::*;
mod admin_table_sort_values;
pub(crate) use crate::admin_table_sort_values::*;
mod admin_text;
pub(crate) use crate::admin_text::*;
mod admin_texts;
pub(crate) use crate::admin_texts::*;
mod admin_update_role_req;
pub(crate) use crate::admin_update_role_req::*;
mod admin_update_role_route;
pub(crate) use crate::admin_update_role_route::*;
mod admin_update_settings_req;
pub(crate) use crate::admin_update_settings_req::*;
mod admin_update_settings_route;
pub(crate) use crate::admin_update_settings_route::*;
mod admin_update_user_req;
pub(crate) use crate::admin_update_user_req::*;
mod admin_update_user_route;
pub(crate) use crate::admin_update_user_route::*;
mod admin_user_id;
pub(crate) use crate::admin_user_id::*;
mod admin_user_summaries;
pub(crate) use crate::admin_user_summaries::*;
mod admin_user_summary;
pub(crate) use crate::admin_user_summary::*;
mod admin_users_page;
pub(crate) use crate::admin_users_page::*;
mod audit_branding;
pub(crate) use crate::audit_branding::*;
mod authenticated_admin;
pub(crate) use crate::authenticated_admin::*;
mod authorization_catalog;
pub(crate) use crate::authorization_catalog::*;
mod collections;
pub(crate) use crate::collections::*;
mod default_admin_api_body_max_bytes;
pub(crate) use crate::default_admin_api_body_max_bytes::*;
#[cfg(test)]
mod domain_types_dto_tests;
#[cfg(test)]
pub(crate) use crate::domain_types_dto_tests::*;
#[cfg(test)]
mod domain_types_query_tests;
#[cfg(test)]
pub(crate) use crate::domain_types_query_tests::*;
#[cfg(test)]
mod domain_types_routes_tests;
#[cfg(test)]
pub(crate) use crate::domain_types_routes_tests::*;
#[cfg(test)]
mod domain_types_sessions_tests;
#[cfg(test)]
pub(crate) use crate::domain_types_sessions_tests::*;
#[cfg(test)]
mod domain_types_settings_tests;
#[cfg(test)]
pub(crate) use crate::domain_types_settings_tests::*;
#[cfg(test)]
mod domain_types_tests;
#[cfg(test)]
pub(crate) use crate::domain_types_tests::*;
mod dto;
pub(crate) use crate::dto::*;
mod identifier;
pub(crate) use crate::identifier::*;
mod identity;
pub(crate) use crate::identity::*;
mod positive_non_zero_i64;
pub(crate) use crate::positive_non_zero_i64::*;
mod query;
pub(crate) use crate::query::*;
mod routes;
pub(crate) use crate::routes::*;
mod serde_json_admin_audit_details;
pub(crate) use crate::serde_json_admin_audit_details::*;
mod sessions;
pub(crate) use crate::sessions::*;
mod settings;
pub(crate) use crate::settings::*;
mod table_sort;
pub(crate) use crate::table_sort::*;

pub mod domain_types;
