[package]
name = "server_app_state"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
description = "Server application state"
repository = "https://github.com/kuqmua/rust_workspace_template"
readme = "../README.md"
keywords = ["server", "state"]
categories = ["web-programming"]

[dependencies]
app_state.workspace = true
chrono.workspace = true
cmn_routes.workspace = true
config_lib.workspace = true
git_info.workspace = true
optml.workspace = true
pg_crud = { workspace = true, features = ["test-utils"] }
server_config.workspace = true
sqlx.workspace = true

[dev-dependencies]
secrecy.workspace = true
tokio.workspace = true

[lints]
workspace = true
