[package]
name = "server_app_state"
version = "0.1.0"
publish = false
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]
edition = "2024"

[dependencies]
str_constants = { workspace = true }
chrono = { workspace = true }
config_lib = { workspace = true }
common_routes = { workspace = true }
git_info = { workspace = true }
app_state = { workspace = true }
server_config = { workspace = true }
server_runtime = { workspace = true }
sqlx = { workspace = true }
pg_table = { workspace = true, features = ["test-utils"] }
optml = { workspace = true }
server_app_state_macros = { workspace = true }
[dev-dependencies]
secrecy = { workspace = true }
tokio = { workspace = true }
[features]
test-utils = []
[lints]
workspace = true
