[package]
name = "server_app_state"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
description = "Server application state"
repository = "https://github.com/kuqmua/rust_workspace_template"
readme = "../README.md"
keywords = ["server", "state"]
categories = ["web-programming"]

[dependencies]
app_state.workspace = true
server_config.workspace = true

[lints]
workspace = true
