[package]
name = "location_test"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dependencies]
str_constants = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
location_lib = { workspace = true }
location_macros = { workspace = true }
location = { workspace = true }
optml = { workspace = true }
newtype = { workspace = true }
to_err_string = { workspace = true }
[lints]
workspace = true
