[package]
name = "text_policy"
version.workspace = true
publish.workspace = true
description = "Shared validation policies for bounded textual domain values"
repository.workspace = true

license.workspace = true
keywords = ["validation", "text"]
categories = ["data-structures"]
edition.workspace = true

[dependencies]
proc_macro_newtype_from_inner = { workspace = true }
proc_macro_newtype_into_inner_from = { workspace = true }
constants_str = { workspace = true }
constants_usize = { workspace = true }
proc_macro_optimal_memory_layout = { workspace = true }
proc_macro_newtype_as_ref_str = { workspace = true }
proc_macro_newtype_into_inner = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
