[package]
name = "pg_json_obj"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
description = "PostgreSQL JSON object leaf types"
repository = "https://github.com/kuqmua/rust_workspace_template"
readme = "../../README.md"
keywords = ["postgres", "json"]
categories = ["database"]

[dependencies]
gen_pg_json_obj.workspace = true
pg_json_obj_cmn.workspace = true

[lints]
workspace = true
