[package]
name = "gen_pg_json_src"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
description = "PostgreSQL JSON source generator"
repository = "https://github.com/kuqmua/rust_workspace_template"
readme = "../../../README.md"
keywords = ["postgres", "generator"]
categories = ["database"]

[dependencies]
gen_quotes.workspace = true
macros_helpers.workspace = true
naming.workspace = true
optml.workspace = true
panic_loc.workspace = true
pg_crud_macros_cmn.workspace = true
proc-macro2.workspace = true
quote.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
token_patterns.workspace = true

[lints]
workspace = true
