[package]
name = "workspace_macro_helpers"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true
[dependencies]
proc_macro_optimal_memory_layout = { workspace = true }
constants_str = { workspace = true }
proc_macro_newtype_foundation_foundation_from_inner = { workspace = true }
proc_macro_newtype_foundation_foundation_get_inner = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
[lints]
workspace = true
