[package]
edition.workspace = true
name = "macros_helpers"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true

[dependencies]
str_constants = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
strum_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
server_runtime_http = { workspace = true }
thiserror = { workspace = true }
token_patterns = { workspace = true }
generate_quotes = { workspace = true }
naming = { workspace = true }
naming_common = { workspace = true }
naming_macros = { workspace = true }
newtype = { workspace = true }
generate_derive_token_stream_builder = { workspace = true }
optml = { workspace = true }
[features]
test-utils = ["dep:serde_json"]
[lints]
workspace = true
