[package]
edition = "2024"
name = "macros_helpers"
version = "0.1.0"
publish = false
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
strum_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }
token_patterns = { workspace = true }
gen_quotes = { workspace = true }
naming = { workspace = true }
naming_cmn = { workspace = true }
naming_macros = { workspace = true }
newtype = { workspace = true }
gen_derive_ts_builder = { workspace = true }
optml = { workspace = true }
[features]
test-utils = ["dep:serde_json"]
[lints]
workspace = true
