[package]
name = "gen_wh_flts_src"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
description = "PostgreSQL where-filter source generator"
repository = "https://github.com/kuqmua/rust_workspace_template"
readme = "../../../README.md"
keywords = ["postgres", "generator"]
categories = ["database"]

[dependencies]
proc-macro2.workspace = true

[lints]
workspace = true
