[package]
name = "administrator_account_initialization_and_password_reset"
version.workspace = true
publish.workspace = true
description = "One-time initial administrator creation command"
repository.workspace = true

license.workspace = true
edition.workspace = true

[dependencies]
proc_macro_new = { workspace = true }
constants_usize = { workspace = true }
proc_macro_optimal_memory_layout = { workspace = true }
app_state = { workspace = true }
config_lib = { workspace = true }
proc_macro_newtype = { workspace = true }
secrecy = { workspace = true }
server_admin = { workspace = true }
server_admin_contract = { workspace = true }
server_config = { workspace = true }
server_runtime_http = { workspace = true }
sqlx = { workspace = true }
constants_str = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
