[package]
name = "pg_types_text_misc"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
description = "PostgreSQL text and miscellaneous leaf types"
repository = "https://github.com/kuqmua/rust_workspace_template"
readme = "../../../README.md"
keywords = ["postgres", "types"]
categories = ["database"]

[dependencies]
gen_pg_types.workspace = true
loc_lib.workspace = true
optml.workspace = true
pg_crud_cmn.workspace = true
pg_types_cmn.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
uuid.workspace = true
wh_flts.workspace = true

[features]
test-utils = ["pg_crud_cmn/test-utils"]

[lints]
workspace = true
