#[derive(
    proc_macro_optimal_memory_layout::OptimalMemoryLayout,
    Debug,
    proc_macro_newtype_debug_display::DebugDisplay,
    thiserror::Error,
)]
pub enum OpenApiValidationError {
    DocumentSerialization(
        crate::serde_json_open_api_serialization_error::SerdeJsonOpenApiSerializationError,
    ),
    MissingOperationId(
        crate::open_api_contract_text::OpenApiContractText,
        crate::open_api_contract_text::OpenApiContractText,
    ),
    MissingPaths,
    MissingSchemaReference(crate::open_api_contract_text::OpenApiContractText),
    MissingSchemas,
    OpenApiRouteMissing(
        crate::open_api_contract_text::OpenApiContractText,
        crate::open_api_contract_text::OpenApiContractText,
    ),
    OperationIdMismatch(
        crate::open_api_contract_text::OpenApiContractText,
        crate::open_api_contract_text::OpenApiContractText,
        crate::open_api_contract_text::OpenApiContractText,
        crate::open_api_contract_text::OpenApiContractText,
    ),
    RuntimeRouteMissing(
        crate::open_api_contract_text::OpenApiContractText,
        crate::open_api_contract_text::OpenApiContractText,
    ),
    TextTooLong(crate::open_api_contract_text::OpenApiContractTextTryFromStringError),
    UnusedSchema(crate::open_api_contract_text::OpenApiContractText),
}
