apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: migration-dns-egress
  namespace: rust-workspace-template
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values: ["application-migrate", "notification-service-migrate"]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
  policyTypes: ["Egress"]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: application-migration-database-egress
  namespace: rust-workspace-template
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: application-migrate
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: database
          podSelector:
            matchLabels:
              app.kubernetes.io/name: application-postgresql
      ports:
        - protocol: TCP
          port: 5432
  policyTypes: ["Egress"]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: notification-service-migration-database-egress
  namespace: rust-workspace-template
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: notification-service-migrate
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: database
          podSelector:
            matchLabels:
              app.kubernetes.io/name: notification-postgresql
      ports:
        - protocol: TCP
          port: 5432
  policyTypes: ["Egress"]
