[package]
name = "common_routes"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dependencies]
generate_accessor = { workspace = true }
constants_usize = { workspace = true }
bounded_types = { workspace = true }
constants_str = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
server_runtime_http = { workspace = true }
sqlx = { workspace = true }
utoipa = { workspace = true }
app_state = { workspace = true }
frontend_contract = { workspace = true }
frontend_contract_macros = { workspace = true }
git_info = { workspace = true }
optimal_memory_layout = { workspace = true }
newtype = { workspace = true }
to_err_string = { workspace = true }
thiserror = { workspace = true }
[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
[lints]
workspace = true
