[package]
name = "common_routes"
version = "0.1.0"
publish = false
description = "Rust microservice workspace component"
repository = "https://github.com/kuqmua/rust_workspace_template"

license = "MIT"
edition = "2024"

[dependencies]
str_constants = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
server_runtime = { workspace = true }
sqlx = { workspace = true }
utoipa = { workspace = true }
app_state = { workspace = true }
git_info = { workspace = true }
optml = { workspace = true }
newtype = { workspace = true }
[dev-dependencies]
serde_json = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
[lints]
workspace = true
