[package]
name = "frontend_contract"
version.workspace = true
publish.workspace = true
description = "Shared typed frontend metadata contracts"
repository.workspace = true

license.workspace = true
keywords = ["frontend", "contract"]
categories = ["web-programming"]
edition.workspace = true

[dependencies]
proc_macro_frontend_contract_derive_typed_route = { workspace = true }
proc_macro_newtype_get_inner = { workspace = true }
proc_macro_newtype_from_inner = { workspace = true }
proc_macro_newtype_into_inner_from = { workspace = true }
proc_macro_newtype_as_ref_inner = { workspace = true }
proc_macro_naming_enum_with_unit_fields_to_upper_snake_case_str = { workspace = true }
proc_macro_getters = { workspace = true }
proc_macro_new = { workspace = true }
constants_usize = { workspace = true }
proc_macro_optimal_memory_layout = { workspace = true }
bounded_types = { workspace = true }
constants_str = { workspace = true }
proc_macro_newtype_as_mut = { workspace = true }
proc_macro_newtype_as_ref_str = { workspace = true }
proc_macro_newtype_as_ref_target = { workspace = true }
proc_macro_newtype_deref_inner = { workspace = true }
proc_macro_newtype_deref_mut_inner = { workspace = true }
proc_macro_newtype_display = { workspace = true }
proc_macro_newtype_from_getter = { workspace = true }
proc_macro_newtype_utoipa_schema = { workspace = true }
proc_macro_newtype_bounded_string_wrapper = { workspace = true }
percent-encoding = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
to_err_string = { workspace = true }
utoipa = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum = { workspace = true }

[dev-dependencies]
constants_u8 = { workspace = true }
futures = { workspace = true }
proc_macro_frontend_contract_derive_route_catalog = { workspace = true }
proc_macro_frontend_contract_derive_route_family = { workspace = true }

[lints]
workspace = true
