[package]
name = "frontend_contract"
version.workspace = true
publish.workspace = true
description = "Shared typed frontend metadata contracts"
repository.workspace = true

license.workspace = true
keywords = ["frontend", "contract"]
categories = ["web-programming"]
edition.workspace = true

[dependencies]
generate_constructor = { workspace = true }
constants_usize = { workspace = true }
optimal_memory_layout = { workspace = true }
bounded_types = { workspace = true }
constants_str = { workspace = true }
newtype = { workspace = true }
percent-encoding = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
to_err_string = { workspace = true }
utoipa = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
axum = { workspace = true }

[dev-dependencies]
constants_u8 = { workspace = true }
frontend_contract_macros = { workspace = true }
futures = { workspace = true }

[lints]
workspace = true
