[package]
name = "proc_macro_newtype_borrow_owned"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc_macro_newtype_shared = { workspace = true }

[lints]
workspace = true
