[package]
name = "naming_common"
version = "0.1.0"
publish = false
description = "Rust microservice workspace component"
repository = "https://github.com/kuqmua/rust_workspace_template"

license = "MIT"
edition = "2024"

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
convert_case = { workspace = true }
naming_common_macros = { workspace = true }
newtype = { workspace = true }

[dev-dependencies]
str_constants = { workspace = true }
[lints]
workspace = true
