[package]
name = "pg_crud_common"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dependencies]
constants_usize = { workspace = true }
constants_u8 = { workspace = true }
constants_u64 = { workspace = true }
constants_u32 = { workspace = true }
constants_u16 = { workspace = true }
constants_i64 = { workspace = true }
bounded_types = { workspace = true }
constants_str = { workspace = true }
generate_accessor = { workspace = true }
text_policy = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
hmac = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
schemars = { workspace = true }
location_lib = { workspace = true }
location_macros = { workspace = true }
location = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
naming = { workspace = true }
naming_common = { workspace = true }
optimal_memory_layout = { workspace = true }
pg_crud_common_macros = { workspace = true }
newtype = { workspace = true }
to_err_string = { workspace = true }
[features]
test-utils = []

[dev-dependencies]
constants_i32 = { workspace = true }
proptest = { workspace = true }
serde_json = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "query_builders"
harness = false

[lints]
workspace = true
