[package]
name = "generate_pg_types_src"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dependencies]
proc_macro_newtype_from_inner = { workspace = true }
proc_macro_newtype_to_tokens = { workspace = true }
proc_macro_newtype_into_inner_from = { workspace = true }
proc_macro_newtype_as_ref_inner = { workspace = true }
proc_macro_getters = { workspace = true }
proc_macro_new = { workspace = true }
proc_macro_newtype_deref_target = { workspace = true }
constants_str = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
pg_crud_macro_common = { workspace = true }
pg_crud_common = { workspace = true }
generate_quotes = { workspace = true }
panic_location = { workspace = true }
macro_helpers = { workspace = true }
naming = { workspace = true }
token_patterns = { workspace = true }
proc_macro_optimal_memory_layout = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
constants_usize = { workspace = true }

[lints]
workspace = true
