[package]
name = "route_validators"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true


[dependencies]
proc_macro_newtype_get_inner = { workspace = true }
proc_macro_newtype_from_inner = { workspace = true }
proc_macro_newtype_to_err_string_as_ref_str = { workspace = true }
proc_macro_newtype_into_inner_from = { workspace = true }
proc_macro_newtype_as_ref_inner = { workspace = true }
proc_macro_location_derive_location = { workspace = true }
constants_str = { workspace = true }
axum = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
http-body = { workspace = true }
bytes = { workspace = true }
git_info = { workspace = true }
location_lib = { workspace = true }
proc_macro_location_bang = { workspace = true }
proc_macro_location_errors_with_location = { workspace = true }
proc_macro_optimal_memory_layout = { workspace = true }
proc_macro_newtype_as_ref_target = { workspace = true }
proc_macro_newtype_deref_target = { workspace = true }
proc_macro_newtype_into_inner = { workspace = true }
proc_macro_newtype_to_err_string = { workspace = true }
to_err_string = { workspace = true }
utoipa = { workspace = true }

[dev-dependencies]
constants_usize = { workspace = true }
proc_macro_newtype_as_ref_owned = { workspace = true }
proc_macro_newtype_deref_inner = { workspace = true }
proc_macro_newtype_deref_mut_inner = { workspace = true }
proc_macro_newtype_display = { workspace = true }
proc_macro_newtype_not_inner = { workspace = true }

[lints]
workspace = true
