[package]
name = "route_validators"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true


[dependencies]
str_constants = { workspace = true }
axum = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
http-body = { workspace = true }
bytes = { workspace = true }
git_info = { workspace = true }
location_lib = { workspace = true }
location_macros = { workspace = true }
location = { workspace = true }
optimal_memory_layout = { workspace = true }
newtype = { workspace = true }
to_err_string = { workspace = true }
utoipa = { workspace = true }
[lints]
workspace = true
