#[test]
fn test_every_status_code_token_view_and_parser_match_declared_contract() {
    [
        (
            crate::status_code::StatusCode::Continue100,
            100u16,
            constants_str::CONTINUE_100,
        ),
        (
            crate::status_code::StatusCode::SwitchingProtocols101,
            101u16,
            constants_str::SWITCHING_PROTOCOLS_101,
        ),
        (
            crate::status_code::StatusCode::Processing102,
            102u16,
            constants_str::PROCESSING_102,
        ),
        (
            crate::status_code::StatusCode::Ok200,
            200u16,
            constants_str::VALUE_200_OK,
        ),
        (
            crate::status_code::StatusCode::Created201,
            201u16,
            constants_str::CREATED_201,
        ),
        (
            crate::status_code::StatusCode::Accepted202,
            202u16,
            constants_str::ACCEPTED_202,
        ),
        (
            crate::status_code::StatusCode::NonAuthoritativeInformation203,
            203u16,
            constants_str::NON_AUTHORITATIVE_INFORMATION_203,
        ),
        (
            crate::status_code::StatusCode::NoContent204,
            204u16,
            constants_str::NO_CONTENT_204,
        ),
        (
            crate::status_code::StatusCode::ResetContent205,
            205u16,
            constants_str::RESET_CONTENT_205,
        ),
        (
            crate::status_code::StatusCode::PartialContent206,
            206u16,
            constants_str::PARTIAL_CONTENT_206,
        ),
        (
            crate::status_code::StatusCode::MultiStatus207,
            207u16,
            constants_str::MULTI_STATUS_207,
        ),
        (
            crate::status_code::StatusCode::AlreadyReported208,
            208u16,
            constants_str::ALREADY_REPORTED_208,
        ),
        (
            crate::status_code::StatusCode::ImUsed226,
            226u16,
            constants_str::IM_USED_226,
        ),
        (
            crate::status_code::StatusCode::MultipleChoices300,
            300u16,
            constants_str::MULTIPLE_CHOICES_300,
        ),
        (
            crate::status_code::StatusCode::MovedPermanently301,
            301u16,
            constants_str::MOVED_PERMANENTLY_301,
        ),
        (
            crate::status_code::StatusCode::Found302,
            302u16,
            constants_str::FOUND_302,
        ),
        (
            crate::status_code::StatusCode::SeeOther303,
            303u16,
            constants_str::SEE_OTHER_303,
        ),
        (
            crate::status_code::StatusCode::NotModified304,
            304u16,
            constants_str::NOT_MODIFIED_304,
        ),
        (
            crate::status_code::StatusCode::UseProxy305,
            305u16,
            constants_str::USE_PROXY_305,
        ),
        (
            crate::status_code::StatusCode::TemporaryRedirect307,
            307u16,
            constants_str::TEMPORARY_REDIRECT_307,
        ),
        (
            crate::status_code::StatusCode::PermanentRedirect308,
            308u16,
            constants_str::PERMANENT_REDIRECT_308,
        ),
        (
            crate::status_code::StatusCode::BadRequest400,
            400u16,
            constants_str::BAD_REQ_400,
        ),
        (
            crate::status_code::StatusCode::Unauthorized401,
            401u16,
            constants_str::UNAUTHORIZED_401,
        ),
        (
            crate::status_code::StatusCode::PaymentRequired402,
            402u16,
            constants_str::PAYMENT_REQUIRED_402,
        ),
        (
            crate::status_code::StatusCode::Forbidden403,
            403u16,
            constants_str::FORBIDDEN_403,
        ),
        (
            crate::status_code::StatusCode::NotFound404,
            404u16,
            constants_str::NOT_FOUND_404,
        ),
        (
            crate::status_code::StatusCode::MethodNotAllowed405,
            405u16,
            constants_str::METHOD_NOT_ALLOWED_405,
        ),
        (
            crate::status_code::StatusCode::NotAcceptable406,
            406u16,
            constants_str::NOT_ACCEPTABLE_406,
        ),
        (
            crate::status_code::StatusCode::ProxyAuthenticationRequired407,
            407u16,
            constants_str::PROXY_AUTHENTICATION_REQUIRED_407,
        ),
        (
            crate::status_code::StatusCode::RequestTimeout408,
            408u16,
            constants_str::REQUEST_TIMEOUT_408,
        ),
        (
            crate::status_code::StatusCode::Conflict409,
            409u16,
            constants_str::CONFLICT_409,
        ),
        (
            crate::status_code::StatusCode::Gone410,
            410u16,
            constants_str::GONE_410,
        ),
        (
            crate::status_code::StatusCode::LengthRequired411,
            411u16,
            constants_str::LENGTH_REQUIRED_411,
        ),
        (
            crate::status_code::StatusCode::PreconditionFailed412,
            412u16,
            constants_str::PRECONDITION_FAILED_412,
        ),
        (
            crate::status_code::StatusCode::PayloadTooLarge413,
            413u16,
            constants_str::PAYLOAD_TOO_LARGE_413,
        ),
        (
            crate::status_code::StatusCode::UriTooLong414,
            414u16,
            constants_str::URI_TOO_LONG_414,
        ),
        (
            crate::status_code::StatusCode::UnsupportedMediaType415,
            415u16,
            constants_str::UNSUPPORTED_MEDIA_TYPE_415,
        ),
        (
            crate::status_code::StatusCode::RangeNotSatisfiable416,
            416u16,
            constants_str::RANGE_NOT_SATISFIABLE_416,
        ),
        (
            crate::status_code::StatusCode::ExpectationFailed417,
            417u16,
            constants_str::EXPECTATION_FAILED_417,
        ),
        (
            crate::status_code::StatusCode::ImATeapot418,
            418u16,
            constants_str::IM_A_TEAPOT_418,
        ),
        (
            crate::status_code::StatusCode::MisdirectedRequest421,
            421u16,
            constants_str::MISDIRECTED_REQ_421,
        ),
        (
            crate::status_code::StatusCode::UnprocessableEntity422,
            422u16,
            constants_str::UNPROCESSABLE_ENTITY_422,
        ),
        (
            crate::status_code::StatusCode::Locked423,
            423u16,
            constants_str::LOCKED_423,
        ),
        (
            crate::status_code::StatusCode::FailedDependency424,
            424u16,
            constants_str::FAILED_DEPENDENCY_424,
        ),
        (
            crate::status_code::StatusCode::UpgradeRequired426,
            426u16,
            constants_str::UPGRADE_REQUIRED_426,
        ),
        (
            crate::status_code::StatusCode::PreconditionRequired428,
            428u16,
            constants_str::PRECONDITION_REQUIRED_428,
        ),
        (
            crate::status_code::StatusCode::TooManyRequests429,
            429u16,
            constants_str::TOO_MANY_REQS_429,
        ),
        (
            crate::status_code::StatusCode::RequestHeaderFieldsTooLarge431,
            431u16,
            constants_str::REQUEST_HEADER_FIELDS_TOO_LARGE_431,
        ),
        (
            crate::status_code::StatusCode::UnavailableForLegalReasons451,
            451u16,
            constants_str::UNAVAILABLE_FOR_LEGAL_REASONS_451,
        ),
        (
            crate::status_code::StatusCode::InternalServerError500,
            500u16,
            constants_str::INTERNAL_SERVER_ERROR_500,
        ),
        (
            crate::status_code::StatusCode::NotImplemented501,
            501u16,
            constants_str::NOT_IMPLEMENTED_501,
        ),
        (
            crate::status_code::StatusCode::BadGateway502,
            502u16,
            constants_str::BAD_GATEWAY_502,
        ),
        (
            crate::status_code::StatusCode::ServiceUnavailable503,
            503u16,
            constants_str::SERVICE_UNAVAILABLE_503,
        ),
        (
            crate::status_code::StatusCode::GatewayTimeout504,
            504u16,
            constants_str::GATEWAY_TIMEOUT_504,
        ),
        (
            crate::status_code::StatusCode::HttpVersionNotSupported505,
            505u16,
            constants_str::HTTP_VERSION_NOT_SUPPORTED_505,
        ),
        (
            crate::status_code::StatusCode::VariantAlsoNegotiates506,
            506u16,
            constants_str::VARIANT_ALSO_NEGOTIATES_506,
        ),
        (
            crate::status_code::StatusCode::InsufficientStorage507,
            507u16,
            constants_str::INSUFFICIENT_STORAGE_507,
        ),
        (
            crate::status_code::StatusCode::LoopDetected508,
            508u16,
            constants_str::LOOP_DETECTED_508,
        ),
        (
            crate::status_code::StatusCode::NotExtended510,
            510u16,
            constants_str::NOT_EXTENDED_510,
        ),
        (
            crate::status_code::StatusCode::NetworkAuthenticationRequired511,
            511u16,
            constants_str::NETWORK_AUTHENTICATION_REQUIRED_511,
        ),
    ]
    .into_iter()
    .fold((), |(), (status, code, parser_text)| {
        assert_eq!(
            status
                .to_status_code_token_stream()
                .as_ref()
                .to_string()
                .parse::<u16>(),
            Ok(code)
        );
        let snake = status.as_snake_case_str();
        assert_eq!(
            crate::status_code::StatusCode::try_from(&parser_text.to_owned()),
            Ok(status)
        );
        let name = snake
            .trim_end_matches(|character: char| character.is_ascii_digit())
            .trim_end_matches('_');
        let description_name = if status == crate::status_code::StatusCode::TooManyRequests429 {
            constants_str::TOO_MANY_REQS_429
                .rsplit_once('_')
                .map_or(name, |(prefix, _suffix)| prefix)
        } else {
            name
        };
        let description = if status == crate::status_code::StatusCode::LengthRequired411 {
            format!(
                "{}{}{}",
                constants_str::LEN,
                constants_str::SPACE,
                constants_str::REQUIRED
            )
        } else {
            description_name.replace('_', constants_str::SPACE)
        };
        assert!(
            syn::parse2::<syn::LitStr>(
                status
                    .to_status_code_description_token_stream()
                    .as_ref()
                    .clone()
            )
            .is_ok_and(|literal| {
                assert_eq!(literal.value(), description, "{status:?}");
                true
            })
        );
        let http_name = name.to_ascii_uppercase();
        assert!(
            syn::parse2::<syn::Path>(status.to_http_status_code_token_stream().as_ref().clone())
                .is_ok_and(|path| {
                    path.segments
                        .iter()
                        .map(|segment| segment.ident.to_string())
                        .eq([
                            stringify!(http).to_owned(),
                            stringify!(StatusCode).to_owned(),
                            http_name,
                        ])
                })
        );
        assert!(
            syn::parse::Parser::parse2(
                syn::Attribute::parse_outer,
                status
                    .to_proc_macro_attr_view_token_stream()
                    .as_ref()
                    .clone()
            )
            .is_ok_and(|attributes| attributes.len() == constants_usize::ONE
                && attributes.first().is_some_and(|attribute| attribute
                    .path()
                    .is_ident(status.to_string().as_str())))
        );
    });
}

#[test]
fn test_status_attribute_selection_preserves_ignored_paths_and_error_precedence() {
    [
        (
            quote::quote!(
                #[http::not_found_404]
                #[unknown(unexpected)]
                Variant
            ),
            Err(crate::only_one_status_code_error::OnlyOneStatusCodeError::NotFound),
        ),
        (
            quote::quote!(
                #[http::not_found_404]
                #[unknown(unexpected)]
                #[not_found_404]
                Variant
            ),
            Ok(crate::status_code::StatusCode::NotFound404),
        ),
        (
            quote::quote!(
                #[not_found_404]
                #[http::internal_server_error_500]
                #[unknown = Value]
                Variant
            ),
            Ok(crate::status_code::StatusCode::NotFound404),
        ),
        (
            quote::quote!(
                #[not_found_404]
                #[not_found_404]
                Variant
            ),
            Err(crate::only_one_status_code_error::OnlyOneStatusCodeError::MoreThanOne),
        ),
        (
            quote::quote!(
                #[not_found_404]
                #[internal_server_error_500(unexpected)]
                Variant
            ),
            Err(crate::only_one_status_code_error::OnlyOneStatusCodeError::MalformedAttribute),
        ),
        (
            quote::quote!(
                #[not_found_404(unexpected)]
                #[not_found_404]
                #[internal_server_error_500]
                Variant
            ),
            Err(crate::only_one_status_code_error::OnlyOneStatusCodeError::MalformedAttribute),
        ),
        (
            quote::quote!(
                #[not_found_404]
                #[internal_server_error_500]
                #[not_found_404(unexpected)]
                Variant
            ),
            Err(crate::only_one_status_code_error::OnlyOneStatusCodeError::MoreThanOne),
        ),
    ]
    .into_iter()
    .fold((), |(), (tokens, expected)| {
        let variant_result = syn::parse2::<syn::Variant>(tokens);
        assert!(variant_result.is_ok());
        let Ok(variant) = variant_result else {
            return;
        };
        assert_eq!(
            crate::only_one::only_one(crate::syn_variant_ref::SynVariantRef::from(&variant)),
            expected
        );
    });
}
