[alias]
workspace-format = "fmt --all"
workspace-lint = "clippy --workspace --all-targets --all-features -- -D warnings"
workspace-test = "test --workspace --all-targets --all-features"
workspace-check-no-default-features = "check --workspace --all-targets --no-default-features"
workspace-doc = "doc --workspace --all-features --no-deps"
workspace-nextest = "nextest run --all-targets --all-features --profile ci"
workspace-hack = "hack check --workspace --feature-powerset --no-dev-deps"
workspace-deny = "deny check advisories bans licenses sources"
workspace-udeps = "+nightly udeps --workspace --all-targets --all-features"
workspace-verify = "!cargo fmt && cargo clippy --all-targets --all-features -- -D warnings && cargo test"
