import { expect, test } from "@playwright/test";
import { signInAdministratorWithPasswordReset } from "./support/admin.js";

test("test_role_rule_details_follow_table_link_and_ignore_list_filters", async ({ page }) => {
  await signInAdministratorWithPasswordReset(page);
  await page.goto("/admin/role_rules");
  const row = page.locator("tbody tr").last();
  const cells = row.locator("td");
  await expect(cells).toHaveCount(5);
  const values = await cells.allTextContents();
  const path = `/admin/role_rules/${values[0].trim()}/read`;
  const link = row.getByRole("link", { name: "read", exact: true });
  await expect(link).toHaveAttribute("href", path);
  await link.click();
  await expect(page).toHaveURL(new RegExp(`${path}$`));
  const detail = page.locator('[data-page="role-rule-read"]');
  await expect(detail.locator(".health-result")).toHaveText(values.slice(0, 4));
  await page.goto(path.replace(/\/read$/, ""));
  await expect(detail.locator(".health-result")).toHaveText(values.slice(0, 4));
  await page.goto(path);
  await page.reload();
  await expect(detail.locator(".health-result")).toHaveText(values.slice(0, 4));
  await page.goto(`${path}?search=missing&offset=999&filter_field=id&filter_operation=eq&filter_value=999`);
  await expect(detail.locator(".health-result")).toHaveText(values.slice(0, 4));
  await page.goto("/admin/role_rules/9223372036854775807/read");
  await expect(detail).toContainText("resource not found");
  await expect(detail.locator(".health-result")).toHaveCount(0);
  await page.goto("/admin/role_rules/1/read");
  await expect(detail.locator(".health-result")).toHaveCount(4);
  await expect(detail.locator(".health-result").first()).toHaveText("1");
});
