[package]
name = "generate_pg_types"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true


[lib]
proc-macro = true

[dependencies]
generate_pg_types_src = { workspace = true }
macros_helpers = { workspace = true }
[lints]
workspace = true
