[package]
name = "server_runtime_core"
version.workspace = true
publish.workspace = true
description = "Dependency-light shared service runtime primitives"
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
proc_macro_getters = { workspace = true }
proc_macro_new = { workspace = true }
constants_usize = { workspace = true }
constants_u8 = { workspace = true }
constants_u64 = { workspace = true }
proc_macro_optimal_memory_layout = { workspace = true }
bounded_types = { workspace = true }
proc_macro_newtype = { workspace = true }
constants_str = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

[lints]
workspace = true
