[package]
name = "proc_macro_to_err_string_impl_to_err_string_with"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc_macro_to_err_string_shared = { workspace = true }

[lints]
workspace = true
