#[path = "table.rs"]
pub(crate) mod table;
#[path = "table_body.rs"]
pub(crate) mod table_body;
#[path = "table_caption.rs"]
pub(crate) mod table_caption;
#[path = "table_cell.rs"]
pub(crate) mod table_cell;
#[path = "table_footer.rs"]
pub(crate) mod table_footer;
#[path = "table_head.rs"]
pub(crate) mod table_head;
#[path = "table_header.rs"]
pub(crate) mod table_header;
#[path = "table_row.rs"]
pub(crate) mod table_row;
#[path = "table_wrapper.rs"]
pub(crate) mod table_wrapper;
