#[path = "domain_types_with_owner_table_table.rs"]
pub(crate) mod table;
#[path = "domain_types_with_owner_table_table_body.rs"]
pub(crate) mod table_body;
#[path = "domain_types_with_owner_table_table_caption.rs"]
pub(crate) mod table_caption;
#[path = "domain_types_with_owner_table_table_cell.rs"]
pub(crate) mod table_cell;
#[path = "domain_types_with_owner_table_table_footer.rs"]
pub(crate) mod table_footer;
#[path = "domain_types_with_owner_table_table_head.rs"]
pub(crate) mod table_head;
#[path = "domain_types_with_owner_table_table_header.rs"]
pub(crate) mod table_header;
#[path = "domain_types_with_owner_table_table_row.rs"]
pub(crate) mod table_row;
#[path = "domain_types_with_owner_table_table_wrapper.rs"]
pub(crate) mod table_wrapper;
