#[path = "admin_data_table_grid.rs"]
pub(crate) mod admin_data_table_grid;
#[path = "admin_role_permissions.rs"]
pub(crate) mod admin_role_permissions;
#[path = "admin_user_roles.rs"]
pub(crate) mod admin_user_roles;
#[path = "pagination.rs"]
pub(crate) mod pagination;
#[path = "domain_types_shared_settings.rs"]
pub(crate) mod settings;
#[path = "table_filters.rs"]
pub(crate) mod table_filters;
#[path = "text.rs"]
pub(crate) mod text;
