// Root-owned module compatibility wrappers.
pub(crate) mod admin_ssr_html_try_from_string_error {}
pub(crate) mod crud_render_role_create {}
pub(crate) mod crud_render_role_manage {}
pub(crate) mod crud_render_shell {}
pub(crate) mod crud_render_user_create {}
pub(crate) mod crud_render_user_manage {}
pub(crate) mod data_table_grid {}
pub(crate) mod data_tables {}
pub(crate) mod document {}
pub(crate) mod render_permissions {}
pub(crate) mod render_profile {}
pub(crate) mod render_roles {}
pub(crate) mod render_sessions {}
pub(crate) mod render_settings {}
pub(crate) mod render_users {}
pub(crate) mod table_pagination {}
pub(crate) mod text_page {}
pub(crate) mod admin_ssr_text_try_from_string_error {}
pub(crate) mod admin_ssr_error_message {}
pub(crate) mod admin_ssr_text {}
pub(crate) mod admin_ssr_html {}
pub(crate) mod render_user_create {}
pub(crate) mod render_user_manage {}
pub(crate) mod render_role_create {}
pub(crate) mod render_role_manage {}
pub(crate) mod render_admin_permissions_page {}
pub(crate) mod render_admin_sessions_page {}
pub(crate) mod render_admin_profile_page {}
pub(crate) mod render_admin_settings_page {}
pub(crate) mod render_view {}
