[package]
name = "generate_where_filters_src"
version = "0.1.0"
publish = false
description = "Rust microservice workspace component"
repository = "https://github.com/kuqmua/rust_workspace_template"

license = "MIT"
edition = "2024"


[dependencies]
str_constants = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
strum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
pg_crud_macros_common = { workspace = true }
generate_quotes = { workspace = true }
panic_location = { workspace = true }
naming = { workspace = true }
newtype = { workspace = true }
token_patterns = { workspace = true }
macros_helpers = { workspace = true }
optml = { workspace = true }
[lints]
workspace = true
