[package]
name = "external_service_emulators"
version.workspace = true
publish.workspace = true
description = "Deterministic external service emulators for integration tests"
repository.workspace = true

license.workspace = true
keywords = ["emulator", "testing"]
categories = ["development-tools::testing"]
edition.workspace = true

[dependencies]
proc_macro_newtype_from_inner = { workspace = true }
proc_macro_newtype_into_inner_from = { workspace = true }
proc_macro_getters = { workspace = true }
constants_usize = { workspace = true }
proc_macro_optimal_memory_layout = { workspace = true }
server_runtime_http = { workspace = true }
constants_str = { workspace = true }
synchronization_service_runtime = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
