[package]
name = "external_service_emulators"
version = "0.1.0"
publish = false
description = "Deterministic external service emulators for integration tests"
repository = "https://github.com/kuqmua/rust_workspace_template"

license = "MIT"
keywords = ["emulator", "testing"]
categories = ["development-tools::testing"]
edition = "2024"

[dependencies]
newtype = { workspace = true }
server_runtime = { workspace = true }
str_constants = { workspace = true }
synchronization_service_runtime = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
