[package]
name = "server_table_example"
version = "0.1.0"
publish = false
description = "Rust microservice workspace component"
repository = "https://github.com/kuqmua/rust_workspace_template"

license = "MIT"
edition = "2024"

[dependencies]
str_constants = { workspace = true }
app_state = { workspace = true }
axum = { workspace = true }
http = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
sqlx = { workspace = true }
utoipa = { workspace = true }
tracing = { workspace = true }
where_filters = { workspace = true }
git_info = { workspace = true }
generate_pg_table = { workspace = true }
futures = { workspace = true }
frontend_contract = { workspace = true }
location_lib = { workspace = true }
location_macros = { workspace = true }
metrics = { workspace = true }
location = { workspace = true }
pg_table = { workspace = true, features = ["test-utils"] }
pg_crud_common = { workspace = true, features = ["test-utils"] }
pg_types_numeric = { workspace = true, features = ["test-utils"] }
pg_types_text_misc = { workspace = true, features = ["test-utils"] }
route_validators = { workspace = true }
server_runtime = { workspace = true }
server_app_state = { workspace = true, features = ["test-utils"] }
tower = { workspace = true }
tokio = { workspace = true }
optml = { workspace = true }
to_err_string = { workspace = true }
[lints]
workspace = true

[features]
test-utils = [
  "pg_table/test-utils",
  "pg_types_numeric/test-utils",
  "pg_types_text_misc/test-utils",
]
