[package]
name = "location_lib"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true


[dependencies]
bounded_types = { workspace = true }
constants_str = { workspace = true }
utoipa = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
schemars = { workspace = true }
git_info = { workspace = true }
config_lib = { workspace = true }
generate_accessor = { workspace = true }
generate_constructor = { workspace = true }
optimal_memory_layout = { workspace = true }
newtype = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
constants_u32 = { workspace = true }
constants_usize = { workspace = true }

[lints]
workspace = true
