[package]
name = "location_lib"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true


[dependencies]
proc_macro_newtype_from_inner = { workspace = true }
proc_macro_newtype_into_inner_from = { workspace = true }
bounded_types = { workspace = true }
constants_str = { workspace = true }
utoipa = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
schemars = { workspace = true }
git_info = { workspace = true }
config_lib = { workspace = true }
proc_macro_getters = { workspace = true }
proc_macro_new = { workspace = true }
proc_macro_optimal_memory_layout = { workspace = true }
proc_macro_newtype_as_ref_str = { workspace = true }
proc_macro_newtype_deref_inner = { workspace = true }
proc_macro_newtype_display = { workspace = true }
proc_macro_newtype_try_from = { workspace = true }
proc_macro_newtype_bounded_string_wrapper = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
constants_u32 = { workspace = true }
constants_usize = { workspace = true }

[lints]
workspace = true
