#[cfg(test)]
mod tests {
    #[test]
    #[allow(clippy::needless_for_each)] // iterator form is required by the workspace no-for-loop policy
    fn test_representative_statuses_cover_every_error_class() {
        [
            (
                http::StatusCode::OK,
                crate::http_error_class::HttpErrorClass::UnexpectedSuccess,
            ),
            (
                http::StatusCode::UNAUTHORIZED,
                crate::http_error_class::HttpErrorClass::Authentication,
            ),
            (
                http::StatusCode::FORBIDDEN,
                crate::http_error_class::HttpErrorClass::Forbidden,
            ),
            (
                http::StatusCode::NOT_FOUND,
                crate::http_error_class::HttpErrorClass::NotFound,
            ),
            (
                http::StatusCode::REQUEST_TIMEOUT,
                crate::http_error_class::HttpErrorClass::Timeout,
            ),
            (
                http::StatusCode::GATEWAY_TIMEOUT,
                crate::http_error_class::HttpErrorClass::Timeout,
            ),
            (
                http::StatusCode::CONFLICT,
                crate::http_error_class::HttpErrorClass::Conflict,
            ),
            (
                http::StatusCode::PAYLOAD_TOO_LARGE,
                crate::http_error_class::HttpErrorClass::PayloadTooLarge,
            ),
            (
                http::StatusCode::UNPROCESSABLE_ENTITY,
                crate::http_error_class::HttpErrorClass::Validation,
            ),
            (
                http::StatusCode::TOO_MANY_REQUESTS,
                crate::http_error_class::HttpErrorClass::RateLimited,
            ),
            (
                http::StatusCode::BAD_GATEWAY,
                crate::http_error_class::HttpErrorClass::ServiceUnavailable,
            ),
            (
                http::StatusCode::SERVICE_UNAVAILABLE,
                crate::http_error_class::HttpErrorClass::ServiceUnavailable,
            ),
            (
                http::StatusCode::BAD_REQUEST,
                crate::http_error_class::HttpErrorClass::Internal,
            ),
        ]
        .into_iter()
        .for_each(|(status, expected)| {
            assert_eq!(
                crate::classify_http_error_status::classify_http_error_status(status.into()),
                expected
            );
        });
    }
}

// Root-owned module compatibility wrappers.
