[package]
name = "pg_types_text_misc"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dependencies]
proc_macro_optimal_memory_layout = { workspace = true }
sqlx = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
proc_macro_generate_pg_types = { workspace = true }
frontend_contract = { workspace = true }
pg_types_common = { workspace = true }
pg_crud_common = { workspace = true }
location_lib = { workspace = true }
proc_macro_location_bang = { workspace = true }
proc_macro_location = { workspace = true }
where_filters = { workspace = true }
to_err_string = { workspace = true }
utoipa = { workspace = true }
[lints]
workspace = true

[features]
test-utils = ["pg_crud_common/test-utils"]
