[package]
name = "frontend_contract_macros"
version.workspace = true
publish.workspace = true
description = "Derive macros for shared typed route contracts"
repository.workspace = true

license.workspace = true
keywords = ["frontend", "contract"]
categories = ["web-programming"]
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
constants_usize = { workspace = true }
generate_accessor = { workspace = true }
generate_constructor = { workspace = true }
optimal_memory_layout = { workspace = true }
newtype = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
constants_str = { workspace = true }
syn = { workspace = true }

[lints]
workspace = true
