[package]
name = "frontend_contract_macros"
version.workspace = true
publish.workspace = true
description = "Derive macros for shared typed route contracts"
repository.workspace = true

license.workspace = true
keywords = ["frontend", "contract"]
categories = ["web-programming"]
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
optml = { workspace = true }
newtype = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
str_constants = { workspace = true }
syn = { workspace = true }

[lints]
workspace = true
