[package]
name = "notification_service_contract"
version.workspace = true
publish.workspace = true
description = "Transport contract owned by the notification microservice"
repository.workspace = true

license.workspace = true
keywords = ["notification", "contract"]
categories = ["web-programming"]
edition.workspace = true

[dependencies]
constants_str = { workspace = true }
optimal_memory_layout = { workspace = true }
frontend_contract = { workspace = true }
newtype = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
constants_usize = { workspace = true }

[lints]
workspace = true
