[package]
name = "prepare_pg_databases"
version.workspace = true
publish.workspace = true
description = "PostgreSQL database preparation command planner"
repository.workspace = true

license.workspace = true
keywords = ["postgresql", "migration"]
categories = ["command-line-utilities"]
edition.workspace = true

[dependencies]
proc_macro_new = { workspace = true }
proc_macro_newtype_get_inner = { workspace = true }
proc_macro_newtype_from_inner = { workspace = true }
proc_macro_newtype_as_ref_inner = { workspace = true }
proc_macro_getters = { workspace = true }
constants_usize = { workspace = true }
proc_macro_optimal_memory_layout = { workspace = true }
bounded_types = { workspace = true }
proc_macro_newtype_as_ref_str = { workspace = true }
proc_macro_newtype_as_ref_target = { workspace = true }
constants_str = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
