apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: application
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: ["rust-workspace-template"]
  selector:
    matchLabels:
      app.kubernetes.io/name: application
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notification-service
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: ["rust-workspace-template"]
  selector:
    matchLabels:
      app.kubernetes.io/name: notification-service
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
