[package]
name = "generate_pg_types_test"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dev-dependencies]
constants_usize = { workspace = true }
optimal_memory_layout = { workspace = true }
constants_str = { workspace = true }
quote = { workspace = true }
frontend_contract = { workspace = true }
macro_clippy_check_common = { workspace = true, features = ["test-utils"] }
generate_pg_types_src = { workspace = true }
macro_helpers = { workspace = true, features = ["test-utils"] }
chrono = { workspace = true }
pg_types_chrono_net = { workspace = true }
pg_types_numeric = { workspace = true }
pg_types_text_misc = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
utoipa = { workspace = true }
[lints]
workspace = true

[features]
test-utils = ["macro_clippy_check_common/test-utils"]
