[package]
name = "pg_json"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
description = "PostgreSQL JSON facade crate"
repository = "https://github.com/kuqmua/rust_workspace_template"
readme = "../../README.md"
keywords = ["postgres", "json"]
categories = ["database"]

[dependencies]
pg_json_nbr.workspace = true
pg_json_other.workspace = true

[features]
test-utils = ["pg_json_nbr/test-utils", "pg_json_other/test-utils"]

[lints]
workspace = true
