[package]
edition = "2024"
name = "generate_pg_table"
version = "0.1.0"
publish = false
description = "Rust microservice workspace component"
repository = "https://github.com/kuqmua/rust_workspace_template"

license = "MIT"

[lib]
proc-macro = true

[dependencies]
generate_pg_table_src = { workspace = true }
macros_helpers = { workspace = true }
[lints]
workspace = true
