// The owner module retains lint-sensitive semantics from the original implementation.
#[allow(clippy::arbitrary_source_item_ordering)]
#[derive(Debug, strum_macros::Display, optimal_memory_layout::OptimalMemoryLayout)]
pub(super) enum PgTypeName {
    Int2,
    Int4,
    Int8,
    Float4,
    Float8,
    SmallSerialInitializationByPg,
    SerialInitializationByPg,
    BigSerialInitializationByPg,
    Money,
    Bool,
    Text,
    Bytea,
    Time,
    Interval,
    Date,
    Timestamp,
    TimestampTz,
    UuidV4InitializationByPg,
    UuidInitializationByClient,
    Inet,
    MacAddr,
    Int4Range,
    Int8Range,
    DateRange,
    TimestampRange,
    TimestampTzRange,
}
impl From<&crate::pg_type::PgType> for PgTypeName {
    fn from(v: &crate::pg_type::PgType) -> Self {
        match &v {
                crate::pg_type::PgType::I16AsInt2 => Self::Int2,
                crate::pg_type::PgType::I32AsInt4 => Self::Int4,
                crate::pg_type::PgType::I64AsInt8 => Self::Int8,
                crate::pg_type::PgType::F32AsFloat4 => Self::Float4,
                crate::pg_type::PgType::F64AsFloat8 => Self::Float8,
                crate::pg_type::PgType::I16AsSmallSerialInitializationByPg => Self::SmallSerialInitializationByPg,
                crate::pg_type::PgType::I32AsSerialInitializationByPg => Self::SerialInitializationByPg,
                crate::pg_type::PgType::I64AsBigSerialInitializationByPg => Self::BigSerialInitializationByPg,
                crate::pg_type::PgType::SqlxPgTypesPgMoneyAsMoney => Self::Money,
                crate::pg_type::PgType::BoolAsBool => Self::Bool,
                crate::pg_type::PgType::StringAsText => Self::Text,
                crate::pg_type::PgType::StdVecVecU8AsBytea => Self::Bytea,
                crate::pg_type::PgType::SqlxTypesChronoNaiveTimeAsTime | crate::pg_type::PgType::SqlxTypesTimeTimeAsTime => Self::Time,
                crate::pg_type::PgType::SqlxPgTypesPgIntervalAsInterval => Self::Interval,
                crate::pg_type::PgType::SqlxTypesChronoNaiveDateAsDate => Self::Date,
                crate::pg_type::PgType::SqlxTypesChronoNaiveDateTimeAsTimestamp => Self::Timestamp,
                crate::pg_type::PgType::SqlxTypesChronoDateTimeSqlxTypesChronoUtcAsTimestampTz => Self::TimestampTz,
                crate::pg_type::PgType::SqlxTypesUuidUuidAsUuidV4InitializationByPg => Self::UuidV4InitializationByPg,
                crate::pg_type::PgType::SqlxTypesUuidUuidAsUuidInitializationByClient => Self::UuidInitializationByClient,
                crate::pg_type::PgType::SqlxTypesIpnetworkIpNetworkAsInet => Self::Inet,
                crate::pg_type::PgType::SqlxTypesMacAddressMacAddressAsMacAddr => Self::MacAddr,
                crate::pg_type::PgType::SqlxPgTypesPgRangeI32AsInt4Range => Self::Int4Range,
                crate::pg_type::PgType::SqlxPgTypesPgRangeI64AsInt8Range => Self::Int8Range,
                crate::pg_type::PgType::SqlxPgTypesPgRangeSqlxTypesChronoNaiveDateAsDateRange => Self::DateRange,
                crate::pg_type::PgType::SqlxPgTypesPgRangeSqlxTypesChronoNaiveDateTimeAsTimestampRange => Self::TimestampRange,
                crate::pg_type::PgType::SqlxPgTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsTimestampTzRange => Self::TimestampTzRange,
            }
    }
}
