// The owner module retains lint-sensitive semantics from the original implementation.
#[allow(clippy::arbitrary_source_item_ordering)]
#[derive(Debug, strum_macros::Display, proc_macro_optimal_memory_layout::OptimalMemoryLayout)]
pub(super) enum PgTypeName {
    Int2,
    Int4,
    Int8,
    Float4,
    Float8,
    SmallSerialInitializationByPg,
    SerialInitializationByPg,
    BigSerialInitializationByPg,
    Money,
    Bool,
    Text,
    Bytea,
    Time,
    Interval,
    Date,
    Timestamp,
    TimestampTz,
    UuidV4InitializationByPg,
    UuidInitializationByClient,
    Inet,
    MacAddr,
    Int4Range,
    Int8Range,
    DateRange,
    TimestampRange,
    TimestampTzRange,
}
impl From<&crate::pg_type_catalog_kind::PgTypeCatalogKind> for PgTypeName {
    fn from(value: &crate::pg_type_catalog_kind::PgTypeCatalogKind) -> Self {
        match &value {
                crate::pg_type_catalog_kind::PgTypeCatalogKind::I16AsInt2 => Self::Int2,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::I32AsInt4 => Self::Int4,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::I64AsInt8 => Self::Int8,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::F32AsFloat4 => Self::Float4,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::F64AsFloat8 => Self::Float8,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::I16AsSmallSerialInitializationByPg => Self::SmallSerialInitializationByPg,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::I32AsSerialInitializationByPg => Self::SerialInitializationByPg,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::I64AsBigSerialInitializationByPg => Self::BigSerialInitializationByPg,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::SqlxPgTypesPgMoneyAsMoney => Self::Money,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::BoolAsBool => Self::Bool,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::StringAsText => Self::Text,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::StdVecVecU8AsBytea => Self::Bytea,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::SqlxTypesChronoNaiveTimeAsTime | crate::pg_type_catalog_kind::PgTypeCatalogKind::SqlxTypesTimeTimeAsTime => Self::Time,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::SqlxPgTypesPgIntervalAsInterval => Self::Interval,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::SqlxTypesChronoNaiveDateAsDate => Self::Date,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::SqlxTypesChronoNaiveDateTimeAsTimestamp => Self::Timestamp,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::SqlxTypesChronoDateTimeSqlxTypesChronoUtcAsTimestampTz => Self::TimestampTz,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::SqlxTypesUuidUuidAsUuidV4InitializationByPg => Self::UuidV4InitializationByPg,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::SqlxTypesUuidUuidAsUuidInitializationByClient => Self::UuidInitializationByClient,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::SqlxTypesIpnetworkIpNetworkAsInet => Self::Inet,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::SqlxTypesMacAddressMacAddressAsMacAddr => Self::MacAddr,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::SqlxPgTypesPgRangeI32AsInt4Range => Self::Int4Range,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::SqlxPgTypesPgRangeI64AsInt8Range => Self::Int8Range,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::SqlxPgTypesPgRangeSqlxTypesChronoNaiveDateAsDateRange => Self::DateRange,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::SqlxPgTypesPgRangeSqlxTypesChronoNaiveDateTimeAsTimestampRange => Self::TimestampRange,
                crate::pg_type_catalog_kind::PgTypeCatalogKind::SqlxPgTypesPgRangeSqlxTypesChronoDateTimeSqlxTypesChronoUtcAsTimestampTzRange => Self::TimestampTzRange,
            }
    }
}
