#[derive(proc_macro_optimal_memory_layout::OptimalMemoryLayout, Clone, Copy)]
pub(super) enum WireKind {
    Bool,
    Bytes,
    Date,
    Float32,
    Float64,
    Inet,
    Int16,
    Int32,
    Int64,
    Interval,
    Mac,
    RangeDate,
    RangeInt32,
    RangeInt64,
    RangeTimestamp,
    RangeTimestampTz,
    String,
    TimeChrono,
    TimeTime,
    Timestamp,
    TimestampTz,
    Uuid,
}
