[package]
name = "generate_where_filters_test"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dev-dependencies]
generate_where_filters_src = { workspace = true }
macro_clippy_check_common = { workspace = true, features = ["test-utils"] }
quote = { workspace = true }
macros_helpers = { workspace = true, features = ["test-utils"] }
serde = { workspace = true }
pg_crud_common = { workspace = true }
where_filters = { workspace = true }
str_constants = { workspace = true }
[lints]
workspace = true

[features]
test-utils = ["macro_clippy_check_common/test-utils"]
