[package]
name = "naming_common"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dependencies]
optimal_memory_layout = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
convert_case = { workspace = true }
naming_common_macros = { workspace = true }
newtype = { workspace = true }

[dev-dependencies]
str_constants = { workspace = true }
[lints]
workspace = true
