[package]
authors = ["sergey shmakov <tyfaproject@gmail.com>"]
edition.workspace = true
name = "server_admin"
version.workspace = true
publish.workspace = true
description = "Reusable administrative API and domain logic"
repository.workspace = true

license.workspace = true
keywords = ["admin"]
categories = ["web-programming"]

[features]
test-utils = []

[dependencies]
constants_usize = { workspace = true }
constants_u64 = { workspace = true }
constants_i64 = { workspace = true }
app_state = { workspace = true }
argon2 = { workspace = true }
axum = { workspace = true }
base16ct = { workspace = true }
bounded_types = { workspace = true }
config_lib = { workspace = true }
futures = { workspace = true }
frontend_contract = { workspace = true }
frontend_contract_macros = { workspace = true }
generate_accessor = { workspace = true }
generate_pg_table = { workspace = true }
git_info = { workspace = true }
http = { workspace = true }
jsonwebtoken = { workspace = true }
location_lib = { workspace = true }
location_macros = { workspace = true }
location = { workspace = true }
metrics = { workspace = true }
newtype = { workspace = true }
optimal_memory_layout = { workspace = true }
pg_crud_common = { workspace = true, features = ["test-utils"] }
pg_table = { workspace = true, features = ["test-utils"] }
pg_types_chrono_net = { workspace = true, features = ["test-utils"] }
pg_types_numeric = { workspace = true, features = ["test-utils"] }
pg_types_text_misc = { workspace = true, features = ["test-utils"] }
reqwest = { workspace = true }
route_validators = { workspace = true }
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
server_admin_contract = { workspace = true }
server_admin_core = { workspace = true }
server_admin_frontend = { workspace = true }
server_observability = { workspace = true }
server_runtime_http = { workspace = true }
server_runtime_core = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true, features = ["macros"] }
constants_str = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
to_err_string = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true }
where_filters = { workspace = true }

[dev-dependencies]
frontend_contract_validation = { workspace = true }

[lints]
workspace = true
