[package]
name = "server_config"
version = "0.1.0"
publish = false
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]
edition = "2024"

[dependencies]
chrono = { workspace = true }
thiserror = { workspace = true }
dotenv = { workspace = true }
secrecy = { workspace = true }
config_lib = { workspace = true }
try_from_env = { workspace = true }
optml = { workspace = true }
[dev-dependencies]
str_constants = { workspace = true }
[lints]
workspace = true
