[package]
name = "server_config"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dependencies]
proc_macro_getters = { workspace = true }
proc_macro_new = { workspace = true }
bounded_types = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
dotenv = { workspace = true }
secrecy = { workspace = true }
config_lib = { workspace = true }
proc_macro_try_from_env = { workspace = true }
proc_macro_optimal_memory_layout = { workspace = true }
constants_str = { workspace = true }
[lints]
workspace = true
