[package]
name = "server_config"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dependencies]
bounded_types = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
dotenv = { workspace = true }
secrecy = { workspace = true }
config_lib = { workspace = true }
try_from_env = { workspace = true }
optimal_memory_layout = { workspace = true }
constants_str = { workspace = true }
[lints]
workspace = true
