#[cfg(feature = "test-utils")]
#[must_use]
pub fn make_test_server_app_state() -> crate::server_app_state::ServerAppState<'static> {
    crate::server_app_state::ServerAppState::new(
        server_runtime_core::resource_budget::ResourceBudget::new(
            server_runtime_core::resource_budget_maximum::ResourceBudgetMaximum::try_from(8usize)
                .expect(constants_str::DIAGNOSTIC_86D3D452),
        ),
        server_config::server_config::ServerConfig::new(
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::ASTERISK.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_512933AF),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::TEST_CONTENT_SECURITY_POLICY.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_957DC3B8),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::TEST_VALUES_UNREACHABLE_DATABASE_URL.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_3E33C100),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::TEST_ONLY_ADMIN_JWT_SECRET_WITH_32_BYTES.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_F29CC79A),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::TEST_AUDIENCE.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_5B218444),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::TEST_ISSUER.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_8357484D),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::VALUE_127_0_0_1_32_PATH_1_128.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_45076555),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::VALUE_900.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_4E1B2430),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::VALUE_1.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_763E1BD9),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::VALUE_10.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_FB8D620E),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::VALUE_3600.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_467A6513),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::VALUE_20.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_B26F4A08),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::VALUE_10.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_53224F39),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::TEST_VALUE_30.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_48634CA9),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::TEST_VALUE_30.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_4D68545F),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::TEST_VALUE_30.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_8B271546),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::TEST_VALUE_30.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_1E6A4C92),
            ),
            config_lib::maximum_size_of_http_body_in_bytes::MaximumSizeOfHttpBodyInBytes::try_from(
                1_024usize,
            )
            .expect(constants_str::DIAGNOSTIC_D7A590E3),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::VALUE_127_0_0_1_3000.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_9CBA6537),
            ),
            config_lib::pg_pool_max_connections::PgPoolMaxConnections::try_from(1u32)
                .expect(constants_str::DIAGNOSTIC_58530F0E),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::VALUE_0.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_D816FC9A),
            ),
            config_lib::chrono_timezone::ChronoTimezone::try_from(
                chrono::FixedOffset::east_opt(10_800i32).expect(constants_str::DIAGNOSTIC_695A2C2A),
            )
            .expect(constants_str::DIAGNOSTIC_E3E42AA5),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::GITHUB_ALT.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_A67F33D1),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(
                    constants_str::CONFIG_TRACING_INFO.to_owned(),
                )
                .expect(constants_str::DIAGNOSTIC_10D6FA4B),
            ),
            config_lib::tracing_format::TracingFormat::Text,
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(constants_str::FALSE.to_owned())
                    .expect(constants_str::DIAGNOSTIC_920EF9AA),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(constants_str::FALSE.to_owned())
                    .expect(constants_str::DIAGNOSTIC_DBE97EF3),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(constants_str::TRUE.to_owned())
                    .expect(constants_str::DIAGNOSTIC_818B46E8),
            ),
            crate::test_env::test_env(
                config_lib::std_env_var_ok::StdEnvVarOk::try_from(constants_str::TRUE.to_owned())
                    .expect(constants_str::DIAGNOSTIC_7C36108E),
            ),
            config_lib::production_mode::ProductionMode::from(false),
            config_lib::svc_mode::SvcMode::Serve,
        ),
        server_runtime_core::resource_budget::ResourceBudget::new(
            server_runtime_core::resource_budget_maximum::ResourceBudgetMaximum::try_from(
                4_096usize,
            )
            .expect(constants_str::DIAGNOSTIC_799DC227),
        ),
        app_state::sqlx_pg_pool::SqlxPgPool::from(
            sqlx::PgPool::connect_lazy(constants_str::TEST_VALUES_UNREACHABLE_DATABASE_URL)
                .expect(constants_str::DIAGNOSTIC_D53D8FF0),
        ),
        git_info::project_git_info_value::project_git_info_value(),
    )
}
