[package]
name = "generate_pg_table_src"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dependencies]
proc_macro_newtype_get_inner = { workspace = true }
proc_macro_newtype_from_inner = { workspace = true }
proc_macro_newtype_into_inner_from = { workspace = true }
bounded_types = { workspace = true }
proc_macro_getters = { workspace = true }
proc_macro_new = { workspace = true }
constants_usize = { workspace = true }
proc_macro_newtype_as_ref_str = { workspace = true }
proc_macro_newtype_deref_inner = { workspace = true }
proc_macro_newtype_display = { workspace = true }
proc_macro_newtype_into_inner = { workspace = true }
proc_macro_newtype_into_iterator = { workspace = true }
proc_macro_newtype_bounded_string_wrapper = { workspace = true }
constants_str = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
strum_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
generate_quotes = { workspace = true }
panic_location = { workspace = true }
macro_helpers = { workspace = true }
pg_crud_common = { workspace = true }
naming = { workspace = true }
naming_common = { workspace = true }
proc_macro_naming_as_ref_str_enum_with_unit_fields_to_upper_camel_case_str = { workspace = true }
proc_macro_naming_as_ref_str_enum_with_unit_fields_to_snake_case_str = { workspace = true }
token_patterns = { workspace = true }
workspace_macro_helpers = { workspace = true }
pg_crud_macro_common = { workspace = true }
proc_macro_optimal_memory_layout = { workspace = true }
thiserror = { workspace = true }
[lints]
workspace = true
