[package]
name = "generate_pg_table_src"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dependencies]
constants_usize = { workspace = true }
newtype = { workspace = true }
constants_str = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
strum_macros = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
generate_quotes = { workspace = true }
panic_location = { workspace = true }
macros_helpers = { workspace = true }
pg_crud_common = { workspace = true }
naming = { workspace = true }
naming_common = { workspace = true }
naming_macros = { workspace = true }
token_patterns = { workspace = true }
workspace_macro_helpers = { workspace = true }
pg_crud_macros_common = { workspace = true }
optimal_memory_layout = { workspace = true }
thiserror = { workspace = true }
[lints]
workspace = true
