[package]
name = "wh_flts"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
description = "PostgreSQL where-filter runtime types"
repository = "https://github.com/kuqmua/rust_workspace_template"
readme = "../../README.md"
keywords = ["postgres", "filters"]
categories = ["database"]

[dependencies]
gen_wh_flts.workspace = true
loc_lib.workspace = true
optml.workspace = true
pg_crud_cmn = { workspace = true, features = ["test-utils"] }
regex.workspace = true
schemars.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
utoipa.workspace = true

[features]
test-utils = ["pg_crud_cmn/test-utils"]

[lints]
workspace = true
