[package]
name = "loc_lib"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
description = "Location domain types"
repository = "https://github.com/kuqmua/rust_workspace_template"
readme = "../README.md"
keywords = ["location"]
categories = ["development-tools"]

[dependencies]
git_info.workspace = true
naming_constants.workspace = true

[lints]
workspace = true
