[package]
name = "constants_str"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true
[dependencies]
git-version = { workspace = true }
constants_str_macros = { workspace = true }
[lints]
workspace = true
