[package]
name = "pg_table"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dependencies]
proc_macro_newtype_get_inner = { workspace = true }
proc_macro_newtype_from_inner = { workspace = true }
proc_macro_newtype_into_inner_from = { workspace = true }
proc_macro_newtype_as_ref_inner = { workspace = true }
constants_usize = { workspace = true }
constants_u8 = { workspace = true }
constants_i64 = { workspace = true }
proc_macro_optimal_memory_layout = { workspace = true }
bounded_types = { workspace = true }
constants_str = { workspace = true }
app_state = { workspace = true }
config_lib = { workspace = true }
proc_macro_getters = { workspace = true }
proc_macro_new = { workspace = true }
proc_macro_newtype_as_mut = { workspace = true }
proc_macro_newtype_as_ref_str = { workspace = true }
proc_macro_newtype_as_ref_target = { workspace = true }
proc_macro_newtype_deref_target = { workspace = true }
proc_macro_newtype_display = { workspace = true }
sha2 = { workspace = true }
server_runtime_core = { workspace = true }
sqlx = { workspace = true }
to_err_string = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
[lints]
workspace = true

[features]
test-utils = []
