[package]
name = "pg_table"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dependencies]
usize_constants = { workspace = true }
u8_constants = { workspace = true }
i64_constants = { workspace = true }
optimal_memory_layout = { workspace = true }
bounded_types = { workspace = true }
str_constants = { workspace = true }
app_state = { workspace = true }
config_lib = { workspace = true }
newtype = { workspace = true }
sha2 = { workspace = true }
server_runtime_http = { workspace = true }
sqlx = { workspace = true }
to_err_string = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
[lints]
workspace = true

[features]
test-utils = []
