[package]
name = "bounded_types"
version.workspace = true
publish.workspace = true
description = "Dependency-light bounded owned text and collection types"
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
constants_usize = { workspace = true }
optimal_memory_layout = { workspace = true }
newtype = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
constants_str = { workspace = true }
thiserror = { workspace = true }
utoipa = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
