#[path = "template_fs_copy_template_tree.rs"]
pub(crate) mod template_fs_copy_template_tree;
#[path = "template_fs_insert_once.rs"]
pub(crate) mod template_fs_insert_once;
#[path = "template_fs_read_bounded_text.rs"]
pub(crate) mod template_fs_read_bounded_text;
#[path = "template_fs_rename_identity.rs"]
pub(crate) mod template_fs_rename_identity;
#[path = "template_fs_replace_file.rs"]
pub(crate) mod template_fs_replace_file;
#[path = "template_fs_should_skip.rs"]
pub(crate) mod template_fs_should_skip;
#[path = "template_fs_write_text.rs"]
pub(crate) mod template_fs_write_text;
