[package]
name = "token_patterns_macros"
version = "0.1.0"
publish = false
description = "Rust microservice workspace component"
repository = "https://github.com/kuqmua/rust_workspace_template"

license = "MIT"
edition = "2024"
[lib]
proc-macro = true
[dependencies]
newtype = { workspace = true }
str_constants = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
workspace_macro_helpers = { workspace = true }
[lints]
workspace = true
