[package]
name = "config_lib"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true


[dependencies]
naming_macros = { workspace = true }
generate_accessor = { workspace = true }
bounded_types = { workspace = true }
secrecy = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
to_err_string = { workspace = true }
dotenv = { workspace = true }
generate_accessor_traits_for_struct_fields = { workspace = true }
optimal_memory_layout = { workspace = true }
config_lib_macros = { workspace = true }
constants_str = { workspace = true }
constants_usize = { workspace = true }
newtype = { workspace = true }

[lints]
workspace = true
