[package]
name = "config_lib"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
description = "Configuration domain types"
repository = "https://github.com/kuqmua/rust_workspace_template"
readme = "../README.md"
keywords = ["configuration", "environment"]
categories = ["config"]

[dependencies]
chrono.workspace = true
dotenv.workspace = true
gen_getter_traits_for_struct_fields.workspace = true
optml.workspace = true
secrecy.workspace = true
serde.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
try_from_env.workspace = true

[lints]
workspace = true
