constants_str_macros::define_str_constants! {
    fragments {}
    constants {
        DISPLAY_NAME_UPDATED_USER = ["{\"display_name\":\"Updated User\"}"];
        IS_BANNED_TRUE_UNKNOWN_TRUE = ["{\"is_banned\":true,\"unknown\":true}"];
        IS_BANNED_TRUE = ["{\"is_banned\":true}"];
        LOGIN_ALT = ["{\"login\":"];
        LOGIN_ADMIN_PASSWORD_PASSWORD = ["{\"login\":\"admin\",\"password\":\"password\"}"];
        LOGIN_ADMIN_PASSWORD_SECRET_UNKNOWN_TRUE = ["{\"login\":\"admin\",\"password\":\"secret\",\"unknown\":true}"];
        LOGIN_LIMITED_USER_DISPLAY_NAME_LIMITED_USER_PASSWORD_LIMITED_PASSWORD = ["{\"login\":\"limited_user\",\"display_name\":\"Limited User\",\"password\":\"Limited-pass1\"}"];
        LOGIN_LIMITED_USER_PASSWORD_LIMITED_PASSWORD = ["{\"login\":\"limited_user\",\"password\":\"Limited-pass1\"}"];
        LOGIN_LOCKED_USER_PASSWORD_WRONG_PASSWORD = ["{\"login\":\"locked_user\",\"password\":\"wrong-password\"}"];
        LOGIN_ADMIN_PASSWORD_CORRECT_PASSWORD = ["{\"login\":\"admin\",\"password\":\"Correct-password1!\"}"];
        CURRENT_PASSWORD_CORRECT_NEW_PASSWORD_CHANGED = ["{\"current_password\":\"Correct-password1!\",\"new_password\":\"Changed-password3!\"}"];
        LOGIN_ADMIN_PASSWORD_WRONG_PASSWORD = ["{\"login\":\"admin\",\"password\":\"wrong-password\"}"];
        NAME_ADMINISTRATOR_UNKNOWN_TRUE = ["{\"name\":\"administrator\",\"unknown\":true}"];
        NAME_RENAMED_ROLE = ["{\"name\":\"renamed_role\"}"];
        NAME_TEMPORARY_ROLE = ["{\"name\":\"temporary_role\"}"];
        OPERATION_RM = ["{\"operation\":\"rm\"}"];
        PASSWORD_SECRET_UNKNOWN_TRUE = ["{\"password\":\"secret\",\"unknown\":true}"];
        PERMISSION_IDS_1_UNKNOWN_TRUE = ["{\"permission_ids\":[1],\"unknown\":true}"];
        ROLE_IDS_1_UNKNOWN_TRUE = ["{\"role_ids\":[1],\"unknown\":true}"];
        SITE_NAME_ADMIN_UNKNOWN_TRUE = ["{\"site_name\":\"Admin\",\"unknown\":true}"];
        VALUE_1_ALT = ["{\"value\":1}"];
        VALUE_7 = ["{\"value\":7}"];
        VALUE_1_2 = ["{\"value\":[1,2]}"];
        COLUMN_ALT = ["{column},"];
        V_ALT = ["{v}"];
        TEXT_ALT_14 = ["{}"];
        USER_AGENT = ["|user-agent="];
        TEXT_ALT_15 = ["~"];
        ASTERISK_ALT = ["~*"];
        VALUE_1_ALT_3 = ["~1"];
        U_3053_U_3093_U_306B_U_3061_U_306F = ["\u{3053}\u{3093}\u{306b}\u{3061}\u{306f}"];
        U_1F30D_U_1F680_U_2728_RUST_U_1F496_U_1F980 = ["\u{1f30d}\u{1f680}\u{2728} Rust \u{1f496}\u{1f980}"];
        U_1F496 = ["\u{1f496}"];
        U_1F600 = ["\u{1f600}"];
        VALUE_08708789 = ["08708789"];
        VALUE_7565757 = ["7565757"];
        VALUE_97697697 = ["97697697"];
        VALUE_123 = ["123"];
        POSTGRES = ["postgres"];
        POSTGRESQL = ["postgresql"];
        LOCALHOST = ["localhost"];
        PATH_1 = ["::1"];
        FAILED_TO_WAIT_FOR_CTRL_C_SIGNAL = ["failed to wait for ctrl-c signal"];
        VALUE_127_0_0_1_32 = ["127.0.0.1/32"];
        VALUE_5C81D907 = ["5c81d907"];
        DELETE = ["DELETE"];
        I64ASNONNULLINT8 = ["I64AsNonNullInt8"];
        I64ASNONNULLBIGSERIALINITIALIZATIONBYPG = ["I64AsNonNullBigSerialInitializationByPg"];
        STATUSCODE = ["StatusCode"];
        HEADER = ["header"];
        HEADERMAP = ["HeaderMap"];
        ROUTE_VALIDATORS = ["route_validators"];
        CHECK_BODY_SIZE = ["check_body_size"];
        MONGODB_DB = ["mongodb://db"];
        REDIS_DB = ["redis://db"];
        GITHUB_ALT = ["GITHUB"];
        DEBUG = ["DeBuG"];
        TRUTHY = ["truthy"];
        VALUE_128 = ["128"];
        VALUE_1K = ["1k"];
        HTTPS_EXAMPLE_COM = ["https://example.com"];
        NAN = ["nan"];
        STD_PATH_FS_PATH_READ = ["std::fs::read"];
        STD_PATH_FS_PATH_READ_TO_STRING = ["std::fs::read_to_string"];
        TOKIO_PATH_FS_PATH_READ = ["tokio::fs::read"];
        TOKIO_PATH_FS_PATH_READ_TO_STRING = ["tokio::fs::read_to_string"];
        TOKIO_PATH_SPAWN = ["tokio::spawn"];
        TOKIO_PATH_TASK_PATH_SPAWN_BLOCKING = ["tokio::task::spawn_blocking"];
        TOKIO_PATH_TASK_PATH_SPAWN_LOCAL = ["tokio::task::spawn_local"];
        STD_PATH_THREAD_PATH_SPAWN = ["std::thread::spawn"];
        RAND_PATH_RNG = ["rand::rng"];
        RAND_PATH_RANDOM = ["rand::random"];
        RAND_PATH_RANDOM_RANGE = ["rand::random_range"];
        RAND_PATH_THREAD_RNG = ["rand::thread_rng"];
        RAND_PATH_RNGS_PATH_OS_RNG = ["rand::rngs::OsRng"];
        RAND_CORE_PATH_OS_RNG = ["rand_core::OsRng"];
        GETRANDOM_PATH_FILL = ["getrandom::fill"];
        GETRANDOM_PATH_U32 = ["getrandom::u32"];
        GETRANDOM_PATH_U64 = ["getrandom::u64"];
        STD_PATH_THREAD_PATH_SLEEP = ["std::thread::sleep"];
        STD_PATH_TIME_PATH_INSTANT_PATH_NOW = ["std::time::Instant::now"];
        STD_PATH_TIME_PATH_SYSTEMTIME_PATH_NOW = ["std::time::SystemTime::now"];
        TOKIO_PATH_TIME_PATH_INSTANT_PATH_NOW = ["tokio::time::Instant::now"];
        PATH_LOCAL_PATH_NOW = ["::Local::now"];
        PATH_FROM_OS_RNG = ["::from_os_rng"];
        COMPILE_ERROR_TOKEN_STREAM = ["compile_error_token_stream"];
        TOML = ["toml"];
        YML = ["yml"];
        YAML = ["yaml"];
        JSON = ["json"];
        BLOCKING_RECV = ["blocking_recv"];
        BLOCKING_SEND = ["blocking_send"];
        TRACING_PATH_DISPATCHER_PATH_SETGLOBALDEFAULTERROR = ["tracing::dispatcher::SetGlobalDefaultError"];
        TRACING_PATH_LOG_PATH_TRACING_PATH_LOG_PATH_SETLOGGERERROR = ["tracing::log::tracing::log::SetLoggerError"];
        VALUE_979FA4B2 = ["979fa4b2"];
        VALUE_589EA31D = ["589ea31d"];
        CREATE_SCHEMA_ADMIN_MIGRATION_FRESH_TEST = ["CREATE SCHEMA admin_migration_fresh_test"];
        TRUNCATE_ADMIN_ACCESS_SESSIONS_ADMIN_REFRESH_TOKENS_ADMIN_LOGIN_ATTEMPTS_ADMIN_RATE = ["TRUNCATE access_sessions, refresh_tokens, login_attempts, rate_limits, audit_log, pg_table_idempotency"];
        NEWLINE_STRUCT_HELPERSTATE_NEWLINE_NAMES_VEC_STRING_NEWLINE_SEEN_STD_PATH_COLLECTIONS = ["\nstruct HelperState {\n    names: Vec<String>,\n    seen: std::collections::BTreeSet<String>,\n    refs: Option<std::collections::HashSet<&'static str>>,\n    wrapped: types::SourceTextList,\n}\nstruct SourceTextList(Vec<String>);\n"];
        INCLUDE_STR_OR_INCLUDE_BYTES_FOUND_OUTSIDE_EXPLICIT_GENERATED_TEST_FIXTURE_ALLOWLIST = ["include_str!() or include_bytes!() found outside explicit generated/test fixture allowlist:"];
        SERVER_ADMIN_REPOSITORY_PATH_SEGMENT = ["server_admin/src/repository/"];
        SERVER_ADMIN_REPOSITORY_AUDIT_RS = ["../server_admin/src/repository/audit.rs"];
        SERVER_ADMIN_REPOSITORY_CLEANUP_RS = ["../server_admin/src/repository/cleanup.rs"];
        SERVER_ADMIN_REPOSITORY_PERMISSIONS_RS = ["../server_admin/src/repository/permissions.rs"];
        SERVER_ADMIN_REPOSITORY_RATE_LIMITS_RS = ["../server_admin/src/repository/rate_limits.rs"];
        SERVER_ADMIN_REPOSITORY_ROLES_RS = ["../server_admin/src/repository/roles.rs"];
        SERVER_ADMIN_REPOSITORY_SESSIONS_RS = ["../server_admin/src/repository/sessions.rs"];
        SERVER_ADMIN_REPOSITORY_SETTINGS_RS = ["../server_admin/src/repository/settings.rs"];
        SERVER_ADMIN_REPOSITORY_USERS_RS = ["../server_admin/src/repository/users.rs"];
        SERVER_ADMIN_CONSTANT_PREFIX = ["SERVER_ADMIN_"];
        SERVER_ADMIN_RECONCILE_PERMISSIONS_SQL = ["insert into permissions (name) select unnest($1::text[]) on conflict (name) do nothing"];
        SERVER_ADMIN_RECONCILE_ROLE_PERMISSIONS_SQL = ["insert into role_permissions (role_id, permission_id) select roles.id, permissions.id from roles cross join permissions where roles.name = 'admin' on conflict (role_id, permission_id) do nothing"];
        SERVER_ADMIN_LOCK_USERS_SQL = ["LOCK TABLE users IN EXCLUSIVE MODE"];
        SERVER_ADMIN_USERS_EXIST_SQL = ["SELECT EXISTS (SELECT 1 FROM users)"];
        SERVER_ADMIN_INSERT_ADMIN_ROLE_SQL = ["INSERT INTO user_roles (user_id, role_id) SELECT $1, id FROM roles WHERE name = 'admin'"];
        SERVER_ADMIN_RECORD_LOGIN_ATTEMPT_SQL = ["WITH attempt AS (INSERT INTO login_attempts (login, ip_address, succeeded) VALUES ($1, $2, $3)) INSERT INTO audit_log (user_login, action, resource, resource_id, request_id, succeeded, details) SELECT $1, 'sign_in', 'session', $1, $4, false, jsonb_build_object('ip_address', $2::INET::text) WHERE $3 = false"];
        SERVER_ADMIN_INSERT_AUDIT_SUCCESS_SQL = ["INSERT INTO audit_log (user_id, user_login, action, resource, resource_id, request_id, succeeded, details) VALUES ($1, $2, $3, $4, $5, $6, true, $7)"];
        SERVER_ADMIN_INSERT_AUDIT_FAILURE_SQL = ["INSERT INTO audit_log (user_id, user_login, action, resource, resource_id, request_id, succeeded, details) VALUES ($1, $2, $3, $4, $5, $6, false, $7)"];
        SERVER_ADMIN_CLEANUP_ACCESS_SESSIONS_SQL = ["WITH expired AS (SELECT id FROM access_sessions WHERE expires_at < now() OR (revoked_at IS NOT NULL AND revoked_at < now() - make_interval(secs => $1)) ORDER BY expires_at LIMIT $2) DELETE FROM access_sessions target USING expired WHERE target.id=expired.id"];
        SERVER_ADMIN_CLEANUP_REFRESH_TOKENS_SQL = ["WITH expired AS (SELECT id FROM refresh_tokens WHERE expires_at < now() OR (revoked_at IS NOT NULL AND revoked_at < now() - make_interval(secs => $1)) ORDER BY expires_at LIMIT $2) DELETE FROM refresh_tokens target USING expired WHERE target.id=expired.id"];
        SERVER_ADMIN_CLEANUP_LOGIN_ATTEMPTS_SQL = ["WITH expired AS (SELECT id FROM login_attempts WHERE attempted_at < now() - make_interval(secs => $1) ORDER BY attempted_at LIMIT $2) DELETE FROM login_attempts target USING expired WHERE target.id=expired.id"];
        SERVER_ADMIN_ENABLE_AUDIT_CLEANUP_SQL = ["SET LOCAL app.admin_audit_cleanup = 'on'"];
        SERVER_ADMIN_CLEANUP_AUDIT_LOG_SQL = ["WITH expired AS (SELECT id FROM audit_log WHERE created_at < now() - make_interval(secs => $1) ORDER BY created_at LIMIT $2) DELETE FROM audit_log target USING expired WHERE target.id=expired.id"];
        SERVER_ADMIN_CLEANUP_RATE_LIMITS_SQL = ["WITH expired AS (SELECT scope,subject FROM rate_limits WHERE window_started_at < now() - make_interval(secs => $1) ORDER BY window_started_at LIMIT $2) DELETE FROM rate_limits target USING expired WHERE target.scope=expired.scope AND target.subject=expired.subject"];
        SERVER_ADMIN_LIST_PERMISSIONS_SQL = ["SELECT id, name FROM permissions ORDER BY name"];
        SERVER_ADMIN_COUNT_FILTERED_USERS_SQL = ["SELECT count(*) FROM users WHERE ($1 = '' OR login ILIKE '%' || $1 || '%' OR display_name ILIKE '%' || $1 || '%' OR id::text = $1)"];
        SERVER_ADMIN_PAGE_USERS_SQL = ["SELECT id, login, display_name, is_banned FROM users WHERE ($1 = '' OR login ILIKE '%' || $1 || '%' OR display_name ILIKE '%' || $1 || '%' OR id::text = $1) ORDER BY CASE WHEN $2 = 'login' AND $3 = 'asc' THEN login END ASC, CASE WHEN $2 = 'login' AND $3 = 'desc' THEN login END DESC, CASE WHEN $2 = 'display_name' AND $3 = 'asc' THEN display_name END ASC, CASE WHEN $2 = 'display_name' AND $3 = 'desc' THEN display_name END DESC, CASE WHEN $2 = 'id' AND $3 = 'asc' THEN id END ASC, CASE WHEN $2 = 'id' AND $3 = 'desc' THEN id END DESC, CASE WHEN $2 = 'status' AND $3 = 'asc' THEN is_banned END ASC, CASE WHEN $2 = 'status' AND $3 = 'desc' THEN is_banned END DESC, id ASC LIMIT $4 OFFSET $5"];
        SERVER_ADMIN_COUNT_FILTERED_ROLES_SQL = ["SELECT count(*) FROM roles WHERE ($1 = '' OR name ILIKE '%' || $1 || '%' OR id::text = $1)"];
        SERVER_ADMIN_PAGE_ROLES_SQL = ["SELECT id, name, is_system FROM roles WHERE ($1 = '' OR name ILIKE '%' || $1 || '%' OR id::text = $1) ORDER BY CASE WHEN $2 = 'name' AND $3 = 'asc' THEN name END ASC, CASE WHEN $2 = 'name' AND $3 = 'desc' THEN name END DESC, CASE WHEN $2 = 'id' AND $3 = 'asc' THEN id END ASC, CASE WHEN $2 = 'id' AND $3 = 'desc' THEN id END DESC, CASE WHEN $2 = 'system' AND $3 = 'asc' THEN is_system END ASC, CASE WHEN $2 = 'system' AND $3 = 'desc' THEN is_system END DESC, id ASC LIMIT $4 OFFSET $5"];
        SERVER_ADMIN_COUNT_FILTERED_PERMISSIONS_SQL = ["SELECT count(*) FROM permissions WHERE ($1 = '' OR name ILIKE '%' || $1 || '%' OR id::text = $1)"];
        SERVER_ADMIN_PAGE_PERMISSIONS_SQL = ["SELECT id, name FROM permissions WHERE ($1 = '' OR name ILIKE '%' || $1 || '%' OR id::text = $1) ORDER BY CASE WHEN $2 = 'name' AND $3 = 'asc' THEN name END ASC, CASE WHEN $2 = 'name' AND $3 = 'desc' THEN name END DESC, CASE WHEN $2 = 'id' AND $3 = 'asc' THEN id END ASC, CASE WHEN $2 = 'id' AND $3 = 'desc' THEN id END DESC, id ASC LIMIT $4 OFFSET $5"];
        SERVER_ADMIN_PAGE_AUDIT_LOG_SQL = ["SELECT id, user_id, user_login, action, resource, resource_id, succeeded, details, created_at::text FROM audit_log WHERE ($1::BIGINT IS NULL OR user_id = $1) AND ($2::text IS NULL OR action = $2) AND ($3::text IS NULL OR resource = $3) AND ($4::TIMESTAMPTZ IS NULL OR created_at >= $4::TIMESTAMPTZ) AND ($5::TIMESTAMPTZ IS NULL OR created_at <= $5::TIMESTAMPTZ) AND ($6::TIMESTAMPTZ IS NULL OR (created_at, id) < ($6::TIMESTAMPTZ, $7::BIGINT)) AND ($8::text IS NULL OR user_login ILIKE '%' || $8 || '%') AND ($9::text IS NULL OR resource_id = $9) AND ($10::boolean IS NULL OR succeeded = $10) ORDER BY created_at DESC, id DESC LIMIT $11 OFFSET $12"];
        SERVER_ADMIN_COUNT_FILTERED_AUDIT_LOG_SQL = ["SELECT count(*) FROM audit_log WHERE ($1::BIGINT IS NULL OR user_id = $1) AND ($2::text IS NULL OR action = $2) AND ($3::text IS NULL OR resource = $3) AND ($4::TIMESTAMPTZ IS NULL OR created_at >= $4::TIMESTAMPTZ) AND ($5::TIMESTAMPTZ IS NULL OR created_at <= $5::TIMESTAMPTZ) AND ($6::text IS NULL OR user_login ILIKE '%' || $6 || '%') AND ($7::text IS NULL OR resource_id = $7) AND ($8::boolean IS NULL OR succeeded = $8)"];
        SERVER_ADMIN_READ_PASSWORD_HASH_SQL = ["SELECT password_hash FROM users WHERE id = $1 AND is_banned = false"];
        SERVER_ADMIN_REVOKE_OTHER_ACCESS_SESSIONS_SQL = ["UPDATE access_sessions SET revoked_at = now() WHERE user_id = $1 AND id <> $2 AND revoked_at IS NULL"];
        SERVER_ADMIN_LIST_ROLE_PERMISSION_IDS_SQL = ["SELECT role_id, permission_id FROM role_permissions WHERE role_id = ANY($1) ORDER BY role_id, permission_id"];
        SERVER_ADMIN_READ_ROLE_PERMISSION_IDS_SQL = ["SELECT permission_id FROM role_permissions WHERE role_id = $1 ORDER BY permission_id"];
        SERVER_ADMIN_LOCK_ROLE_SYSTEM_STATE_SQL = ["SELECT is_system FROM roles WHERE id = $1 FOR UPDATE"];
        SERVER_ADMIN_COUNT_PERMISSIONS_SQL = ["SELECT count(*) FROM permissions WHERE id = ANY($1)"];
        SERVER_ADMIN_REPLACE_ROLE_PERMISSIONS_DELETE_SQL = ["DELETE FROM role_permissions WHERE role_id = $1"];
        SERVER_ADMIN_REPLACE_ROLE_PERMISSIONS_INSERT_SQL = ["INSERT INTO role_permissions (role_id, permission_id) SELECT $1, permission_id FROM unnest($2::bigint[]) AS permission_id"];
        SERVER_ADMIN_ENFORCE_RATE_LIMIT_SQL = ["INSERT INTO rate_limits (scope, subject, window_started_at, request_count) VALUES ($1, $2, now(), 1) ON CONFLICT (scope, subject) DO UPDATE SET window_started_at = CASE WHEN rate_limits.window_started_at <= now() - make_interval(secs => $4) THEN now() ELSE rate_limits.window_started_at END, request_count = CASE WHEN rate_limits.window_started_at <= now() - make_interval(secs => $4) THEN 1 ELSE rate_limits.request_count + 1 END RETURNING request_count <= $3"];
        SERVER_ADMIN_INSERT_ROLE_SQL = ["INSERT INTO roles (name, is_system) VALUES ($1, false) RETURNING id"];
        SERVER_ADMIN_UPDATE_ROLE_SQL = ["UPDATE roles SET name = $2 WHERE id = $1 AND is_system = false RETURNING true"];
        SERVER_ADMIN_DELETE_ROLE_SQL = ["DELETE FROM roles WHERE id = $1 AND is_system = false RETURNING true"];
        SERVER_ADMIN_LIST_ROLES_SQL = ["SELECT id, name, is_system FROM roles ORDER BY name"];
        SERVER_ADMIN_LOCK_USER_ACTIVE_STATE_SQL = ["SELECT NOT is_banned FROM users WHERE id = $1 FOR UPDATE"];
        SERVER_ADMIN_COUNT_ROLES_SQL = ["SELECT count(*) FROM roles WHERE id = ANY($1)"];
        SERVER_ADMIN_READ_ADMIN_ROLE_ID_SQL = ["SELECT id FROM roles WHERE name = 'admin' AND is_system = true"];
        SERVER_ADMIN_USER_HAS_ROLE_SQL = ["SELECT EXISTS (SELECT 1 FROM user_roles WHERE user_id = $1 AND role_id = $2)"];
        SERVER_ADMIN_ACTIVE_ROLE_USER_COUNT_SQL = ["SELECT count(DISTINCT users.id) FROM users users JOIN user_roles user_role ON user_role.user_id = users.id WHERE user_role.role_id = $1 AND users.is_banned = false"];
        SERVER_ADMIN_REPLACE_USER_ROLES_DELETE_SQL = ["DELETE FROM user_roles WHERE user_id = $1"];
        SERVER_ADMIN_REPLACE_USER_ROLES_INSERT_SQL = ["INSERT INTO user_roles (user_id, role_id) SELECT $1, role_id FROM unnest($2::bigint[]) AS role_id"];
        SERVER_ADMIN_READ_USER_ROLE_IDS_SQL = ["SELECT role_id FROM user_roles WHERE user_id = $1 ORDER BY role_id"];
        SERVER_ADMIN_LOCK_LAST_ADMIN_SQL = ["SELECT pg_advisory_xact_lock(hashtext('admin_last_active_administrator'))"];
        SERVER_ADMIN_USER_IS_ADMIN_SQL = ["SELECT EXISTS (SELECT 1 FROM user_roles user_role JOIN roles role ON role.id = user_role.role_id WHERE user_role.user_id = $1 AND role.name = 'admin')"];
        SERVER_ADMIN_ACTIVE_ADMIN_COUNT_SQL = ["SELECT count(DISTINCT users.id) FROM users users JOIN user_roles user_role ON user_role.user_id = users.id JOIN roles role ON role.id = user_role.role_id WHERE role.name = 'admin' AND users.is_banned = false"];
        SERVER_ADMIN_REVOKE_ACCESS_SESSION_SQL = ["UPDATE access_sessions SET revoked_at = now() WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL"];
        SERVER_ADMIN_REVOKE_USER_ACCESS_SESSIONS_SQL = ["UPDATE access_sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL"];
        SERVER_ADMIN_REVOKE_USER_REFRESH_TOKENS_SQL = ["UPDATE refresh_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL"];
        SERVER_ADMIN_READ_ACTIVE_USER_LOGIN_SQL = ["SELECT login FROM users WHERE id = $1 AND is_banned = false"];
        SERVER_ADMIN_LIST_ACTIVE_SESSIONS_SQL = ["SELECT id, created_at::text, expires_at::text FROM access_sessions WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now() ORDER BY created_at DESC LIMIT $2 OFFSET $3"];
        SERVER_ADMIN_COUNT_ACTIVE_SESSIONS_SQL = ["SELECT count(*) FROM access_sessions WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()"];
        SERVER_ADMIN_ACTIVE_ACCESS_SESSION_SQL = ["SELECT EXISTS (SELECT 1 FROM access_sessions session JOIN users users ON users.id = session.user_id WHERE session.id = $1 AND session.user_id = $2 AND session.token_context_hash = $3 AND session.revoked_at IS NULL AND session.expires_at > now() AND users.is_banned = false)"];
        SERVER_ADMIN_READ_CSRF_HASH_SQL = ["SELECT csrf_token_hash FROM access_sessions WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL AND expires_at > now()"];
        SERVER_ADMIN_REVOKE_EXCESS_ACCESS_SESSIONS_SQL = ["UPDATE access_sessions SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL AND id IN (SELECT id FROM access_sessions WHERE user_id = $1 AND revoked_at IS NULL ORDER BY created_at DESC OFFSET $2)"];
        SERVER_ADMIN_REVOKE_EXCESS_REFRESH_TOKENS_SQL = ["UPDATE refresh_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL AND id IN (SELECT id FROM refresh_tokens WHERE user_id = $1 AND revoked_at IS NULL ORDER BY created_at DESC OFFSET $2)"];
        SERVER_ADMIN_INSERT_ACCESS_SESSION_SQL = ["INSERT INTO access_sessions (id, user_id, token_identifier_hash, token_context_hash, csrf_token_hash, expires_at) VALUES ($1, $2, $3, $4, $5, now() + ($6 * interval '1 second'))"];
        SERVER_ADMIN_INSERT_REFRESH_TOKEN_SQL = ["INSERT INTO refresh_tokens (id, user_id, token_hash, expires_at) VALUES ($1, $2, $3, now() + ($4 * interval '1 second'))"];
        SERVER_ADMIN_READ_SETTINGS_SQL = ["SELECT site_name, tab_title, main_logo, primary_color, default_admin_route, organization_name, organization_contacts, support_url FROM system_settings WHERE id = 1"];
        SERVER_ADMIN_RECORD_CLEANUP_STATUS_SQL = ["INSERT INTO cleanup_status (singleton, last_success_at, last_deleted_rows) VALUES (true, now(), $1) ON CONFLICT (singleton) DO UPDATE SET last_success_at = EXCLUDED.last_success_at, last_deleted_rows = EXCLUDED.last_deleted_rows"];
        SERVER_ADMIN_READ_CLEANUP_STATUS_SQL = ["SELECT last_success_at::text, last_deleted_rows FROM cleanup_status WHERE singleton = true"];
        SERVER_ADMIN_DATA_SELECT_ARRAY_PREFIX = ["SELECT ARRAY["];
        SERVER_ADMIN_DATA_SELECT_COLUMN_PREFIX = ["left("];
        SERVER_ADMIN_DATA_SELECT_COLUMN_SUFFIX = ["::text, 8192)"];
        SERVER_ADMIN_DATA_SELECT_FROM = ["] FROM "];
        SERVER_ADMIN_DATA_COUNT_PREFIX = ["SELECT COUNT(*) FROM "];
        SERVER_ADMIN_DATA_ORDER_CREATED_AT = ["created_at DESC, id DESC"];
        SERVER_ADMIN_DATA_ORDER_ATTEMPTED_AT = ["attempted_at DESC, id DESC"];
        SERVER_ADMIN_DATA_ORDER_SINGLETON = ["singleton"];
        SERVER_ADMIN_DATA_ORDER_WINDOW = ["window_started_at DESC, scope, subject"];
        SERVER_ADMIN_FILTER_ENCODE_FORMAT_FIELD = ["encode_format"];
        SERVER_ADMIN_FILTER_ENCODED_VALUE_FIELD = ["encoded_string_representation"];
        SERVER_ADMIN_FILTER_REGEX_CASE_FIELD = ["regex_case"];
        SERVER_ADMIN_FILTER_OPERATOR_AND = ["And"];
        SERVER_ADMIN_FILTER_REGEX_SENSITIVE = ["Sensitive"];
        SERVER_ADMIN_FILTER_ENCODE_BASE64 = ["Base64"];
        SERVER_ADMIN_FILTER_ORDER_BY_SEPARATOR = [" ORDER BY "];
        SERVER_ADMIN_FILTER_LIMIT_SEPARATOR = [" LIMIT $1 OFFSET $2"];
        SERVER_ADMIN_FILTER_LIMIT_PREFIX = [" LIMIT $"];
        SERVER_ADMIN_FILTER_OFFSET_PREFIX = [" OFFSET $"];
        SERVER_ADMIN_DATA_AUDIT_LOG_COLUMNS = ["id,user_id,user_login,action,resource,resource_id,request_id,succeeded,details,created_at"];
        SERVER_ADMIN_DATA_CLEANUP_STATUS_COLUMNS = ["singleton,last_success_at,last_deleted_rows"];
        SERVER_ADMIN_DATA_LOGIN_ATTEMPTS_COLUMNS = ["id,login,ip_address,succeeded,attempted_at"];
        SERVER_ADMIN_DATA_PERMISSIONS_COLUMNS = ["id,name,created_at"];
        SERVER_ADMIN_DATA_RATE_LIMITS_COLUMNS = ["scope,subject,window_started_at,request_count"];
        SERVER_ADMIN_DATA_SESSION_COLUMNS = ["id,user_id,expires_at,created_at,revoked_at"];
        SERVER_ADMIN_DATA_ROLE_PERMISSIONS_COLUMNS = ["id,role_id,permission_id,created_at"];
        SERVER_ADMIN_DATA_ROLES_COLUMNS = ["id,name,is_system,created_at,updated_at"];
        SERVER_ADMIN_DATA_SYSTEM_SETTINGS_COLUMNS = ["id,site_name,tab_title,main_logo,primary_color,default_admin_route,organization_name,organization_contacts,support_url,updated_at"];
        SERVER_ADMIN_DATA_USER_ROLES_COLUMNS = ["id,user_id,role_id,created_at"];
        SERVER_ADMIN_DATA_USERS_COLUMNS = ["id,login,display_name,is_banned,created_at,updated_at"];
        SELECT_MUST_CHANGE_PASSWORD_FROM_ADMIN_USERS_WHERE_LOGIN_ADMIN = ["SELECT must_change_password FROM users WHERE login = 'admin'"];
        UPDATE_ADMIN_USERS_SET_MUST_CHANGE_PASSWORD_FALSE = ["UPDATE users SET must_change_password = false"];
        SERVER_ADMIN_DATA_NULL = ["NULL"];
        USER_BANNED_NOTICE = ["User banned"];
        USER_UNBANNED_NOTICE = ["User unbanned"];
        USER_ROLES_UPDATED_NOTICE = ["User roles updated"];
        ROLE_PERMISSIONS_UPDATED_NOTICE = ["Role permissions updated"];
        SELECT_PG_ADVISORY_XACT_LOCK_ADMIN_TESTS = ["SELECT pg_advisory_xact_lock(734905219)"];
        SERVER_ADMIN_UPDATE_SETTINGS_SQL = ["UPDATE system_settings SET site_name = COALESCE($1, site_name), tab_title = CASE WHEN $9 THEN 'Admin' ELSE COALESCE($2, tab_title) END, main_logo = CASE WHEN $10 THEN 'https://example.com/admin-logo.svg' ELSE COALESCE($3, main_logo) END, primary_color = CASE WHEN $11 THEN '#5b55e7' ELSE COALESCE($4, primary_color) END, default_admin_route = COALESCE($5, default_admin_route), organization_name = CASE WHEN $12 THEN 'Admin' ELSE COALESCE($6, organization_name) END, organization_contacts = CASE WHEN $13 THEN 'support@example.com' ELSE COALESCE($7, organization_contacts) END, support_url = CASE WHEN $14 THEN 'https://example.com/support' ELSE COALESCE($8, support_url) END WHERE id = 1 RETURNING true"];
        SERVER_ADMIN_INSERT_USER_SQL = ["INSERT INTO users (login, display_name, password_hash) VALUES ($1, $2, $3) RETURNING id"];
        SERVER_ADMIN_RECENT_LOGIN_FAILURE_COUNT_SQL = ["SELECT count(*) FROM login_attempts WHERE login = $1 AND succeeded = false AND attempted_at > now() - interval '15 minutes'"];
        SERVER_ADMIN_SIGN_IN_USER_SQL = ["SELECT id, password_hash, is_banned FROM users WHERE lower(login) = lower($1)"];
        SERVER_ADMIN_USER_ID_BY_LOGIN_SQL = ["SELECT id FROM users WHERE lower(login) = lower($1)"];
        SERVER_ADMIN_LOCK_REFRESH_TOKEN_USER_SQL = ["SELECT user_id FROM refresh_tokens WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now() FOR UPDATE"];
        SERVER_ADMIN_REVOKE_REFRESH_TOKEN_SQL = ["UPDATE refresh_tokens SET revoked_at = now() WHERE token_hash = $1 AND user_id = $2 AND revoked_at IS NULL"];
        SERVER_ADMIN_UPDATE_USER_SQL = ["UPDATE users SET login = COALESCE($2, login), display_name = COALESCE($3, display_name) WHERE id = $1 RETURNING true"];
        SERVER_ADMIN_UPDATE_USER_PASSWORD_SQL = ["UPDATE users SET password_hash = $2, must_change_password = $3 WHERE id = $1 RETURNING true"];
        SERVER_ADMIN_UPDATE_USER_BAN_SQL = ["UPDATE users SET is_banned = $2 WHERE id = $1 RETURNING true"];
        SERVER_ADMIN_DELETE_USER_SQL = ["DELETE FROM users WHERE id = $1 RETURNING true"];
        SERVER_ADMIN_LIST_USER_ROLE_IDS_SQL = ["SELECT user_id, role_id FROM user_roles WHERE user_id = ANY($1) ORDER BY user_id, role_id"];
        SERVER_ADMIN_READ_AUTH_USER_SQL = ["SELECT login, display_name, must_change_password FROM users WHERE id = $1 AND is_banned = false"];
        SERVER_ADMIN_READ_AUTH_ROLES_SQL = ["SELECT role.name FROM roles role JOIN user_roles link ON link.role_id = role.id WHERE link.user_id = $1 ORDER BY role.name LIMIT 10001"];
        SERVER_ADMIN_READ_AUTH_PERMISSIONS_SQL = ["SELECT DISTINCT permission.name FROM permissions permission JOIN role_permissions role_permission ON role_permission.permission_id = permission.id JOIN user_roles user_role ON user_role.role_id = role_permission.role_id WHERE user_role.user_id = $1 ORDER BY permission.name LIMIT 10001"];
    }
}
