[package]
name = "generate_derive_token_stream_builder"
version = "0.1.0"
publish = false
description = "Rust microservice workspace component"
repository = "https://github.com/kuqmua/rust_workspace_template"

license = "MIT"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
serde_json = { workspace = true }
naming = { workspace = true }
naming_common = { workspace = true }
optml = { workspace = true }
newtype = { workspace = true }
[lints]
workspace = true
