[package]
name = "workspace_test_runner"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true
[dependencies]
constants_usize = { workspace = true }
constants_u64 = { workspace = true }
constants_u128 = { workspace = true }
constants_i32 = { workspace = true }
constants_i64 = { workspace = true }
optimal_memory_layout = { workspace = true }
bounded_types = { workspace = true }
constants_str = { workspace = true }
generate_pg_table_src = { workspace = true }
generate_pg_types_src = { workspace = true }
generate_where_filters_src = { workspace = true }
frontend_contract = { workspace = true }
macros_helpers = { workspace = true, features = ["test-utils"] }
newtype = { workspace = true }
pg_crud_common = { workspace = true }
quote = { workspace = true }
server_admin_contract = { workspace = true }
server_admin = { workspace = true }
serde_json = { workspace = true }
server_runtime_http = { workspace = true }
token_patterns = { workspace = true }
thiserror = { workspace = true }
utoipa = { workspace = true }
where_filters = { workspace = true }
[lints]
workspace = true
