[package]
name = "workspace_test_runner"
version = "0.1.0"
publish = false
description = "Rust microservice workspace component"
repository = "https://github.com/kuqmua/rust_workspace_template"

license = "MIT"
edition = "2024"
[dependencies]
str_constants = { workspace = true }
generate_pg_table_src = { workspace = true }
generate_pg_types_src = { workspace = true }
generate_where_filters_src = { workspace = true }
frontend_contract = { workspace = true }
macros_helpers = { workspace = true, features = ["test-utils"] }
newtype = { workspace = true }
pg_crud_common = { workspace = true }
quote = { workspace = true }
server_admin_contract = { workspace = true }
server_admin = { workspace = true }
serde_json = { workspace = true }
token_patterns = { workspace = true }
utoipa = { workspace = true }
where_filters = { workspace = true }
[lints]
workspace = true
