[package]
name = "pg_crud_cmn"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false
description = "Shared PostgreSQL CRUD runtime types"
repository = "https://github.com/kuqmua/rust_workspace_template"
readme = "../../README.md"
keywords = ["postgres", "crud"]
categories = ["database"]

[dependencies]
loc_lib.workspace = true
naming.workspace = true
optml.workspace = true
proc-macro2.workspace = true
quote.workspace = true
schemars.workspace = true
serde.workspace = true
sqlx.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
utoipa.workspace = true
uuid.workspace = true

[features]
test-utils = []

[lints]
workspace = true
