[package]
name = "server_runtime_http"
version.workspace = true
publish.workspace = true
description = "Shared HTTP server runtime and integration primitives"
repository.workspace = true

license.workspace = true
keywords = ["server"]
categories = ["web-programming"]
edition.workspace = true

[dependencies]
generate_constructor = { workspace = true }
constants_i32 = { workspace = true }
constants_i64 = { workspace = true }
constants_usize = { workspace = true }
constants_u8 = { workspace = true }
constants_u64 = { workspace = true }
optimal_memory_layout = { workspace = true }
newtype = { workspace = true }
server_observability = { workspace = true }
constants_str = { workspace = true }
text_policy = { workspace = true }
axum = { workspace = true }
bounded_types = { workspace = true }
cookie = { workspace = true }
geojson = { workspace = true }
http = { workspace = true }
ipnet = { workspace = true }
metrics = { workspace = true }
mime = { workspace = true }
opentelemetry = { workspace = true }
percent-encoding = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
uuid = { workspace = true }
[dev-dependencies]
server_runtime_core = { workspace = true }
constants_u16 = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["testing"] }
tokio = { workspace = true, features = ["test-util"] }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
