[package]
name = "generate_quotes"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true


[dependencies]
optimal_memory_layout = { workspace = true }
str_constants = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
newtype = { workspace = true }
[lints]
workspace = true
