name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CARGO_NET_TIMEOUT: 60
  RUSTFLAGS: "-D warnings -D unreachable_pub -D dead_code"
  RUSTDOCFLAGS: "-D warnings"
  RUST_BACKTRACE: short

jobs:
  fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2
        with:
          components: rustfmt
      - run: cargo fmt
      - name: git diff --exit-code
        run: git diff --exit-code

  metadata:
    name: cargo metadata --locked --format-version 1
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2
      - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae
        with:
          cache-on-failure: true
      - name: cargo metadata --locked --format-version 1
        run: cargo metadata --locked --format-version 1

  clippy:
    name: cargo clippy --all-targets --all-features -- -D warnings
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8
        with:
          toolchain: nightly
          components: clippy
      - uses: Swatinem/rust-cache@42dc69e1aa15d09112580998cf2ef0119e2e91ae
        with:
          cache-on-failure: true
          key: clippy-nightly
      - name: cargo clippy --all-targets --all-features -- -D warnings
        run: cargo clippy --all-targets --all-features -- -D warnings

  taplo:
    name: taplo fmt --check
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Install taplo
        uses: taiki-e/install-action@5292d65c95e72dc79f25946b7ce34e28deecf2f3
      - name: taplo fmt --check
        run: taplo fmt --check

  typos:
    name: typos
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Install typos
        uses: taiki-e/install-action@dc6aaebcb47625f80d5dada4c7fbf1dc3e7e257a
      - name: typos
        run: typos

  actionlint:
    name: actionlint
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: rhysd/actionlint@914e7df21a07ef503a81201c76d2b11c789d3fca

  deny:
    name: cargo deny check advisories bans licenses sources
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8
      - name: Install cargo-deny
        uses: taiki-e/install-action@43d63066c313f326186510e6e5feab4dd2391cfd
      - name: cargo deny check advisories bans licenses sources
        run: cargo deny check advisories bans licenses sources

  machete:
    name: cargo machete
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2
      - name: Install cargo-machete
        uses: taiki-e/install-action@59979a424d2584f3cdeca89833d69ca54b72d84f
      - run: cargo machete

  check-semver:
    name: cargo-semver-checks-action
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2
      - uses: obi1kenobi/cargo-semver-checks-action@6b69fcf40e9b5fb17adeb57e4b6ecd020649a239

  hack:
    name: cargo hack check --workspace --feature-powerset --no-dev-deps
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8
      - name: Install cargo-hack
        uses: taiki-e/install-action@a8bfb6e9b2cf3cefc208e6a18507d78669d398ab
      - name: cargo hack check --workspace --feature-powerset --no-dev-deps
        run: cargo hack check --workspace --feature-powerset --no-dev-deps

  udeps:
    name: cargo +nightly udeps --workspace --all-targets --all-features
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: dtolnay/rust-toolchain@5b842231ba77f5c045dba54ac5560fed2db780e2
      - name: Install cargo-udeps
        uses: taiki-e/install-action@b11d693c7febff734da6b5acd9cea3cbb8596ddd
      - name: cargo +nightly udeps --workspace --all-targets --all-features
        run: cargo +nightly udeps --workspace --all-targets --all-features

  llvm-cov:
    name: cargo llvm-cov --workspace --all-features --all-targets --summary-only
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8
        with:
          components: llvm-tools-preview
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@87d97b95c884523e049410b5322ea91b2acdbc89
      - name: cargo llvm-cov --workspace --all-features --all-targets --summary-only
        run: cargo llvm-cov --workspace --all-features --all-targets --summary-only
