[package]
name = "macro_clippy_check_common"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dependencies]
constants_usize = { workspace = true }
constants_i32 = { workspace = true }
optimal_memory_layout = { workspace = true }
constants_str = { workspace = true }
generate_accessor = { workspace = true }
macro_helpers = { workspace = true, optional = true }
server_runtime_http = { workspace = true, optional = true }

[dev-dependencies]
newtype = { workspace = true }

[features]
test-utils = [
  "dep:macro_helpers",
  "dep:server_runtime_http",
]

[lints]
workspace = true
