[package]
name = "macro_clippy_check_common"
version = "0.1.0"
publish = false
description = "Rust microservice workspace component"
repository = "https://github.com/kuqmua/rust_workspace_template"

license = "MIT"
edition = "2024"

[dependencies]
str_constants = { workspace = true }
macros_helpers = { workspace = true, optional = true }
server_runtime = { workspace = true, optional = true }

[features]
test-utils = ["dep:macros_helpers", "dep:server_runtime"]

[lints]
workspace = true
