[package]
name = "macro_clippy_check_common"
version.workspace = true
publish.workspace = true
description.workspace = true
repository.workspace = true

license.workspace = true
edition.workspace = true

[dependencies]
optml = { workspace = true }
str_constants = { workspace = true, optional = true }
macros_helpers = { workspace = true, optional = true }
server_runtime_http = { workspace = true, optional = true }

[dev-dependencies]
newtype = { workspace = true }

[features]
test-utils = [
  "dep:macros_helpers",
  "dep:server_runtime_http",
  "dep:str_constants",
]

[lints]
workspace = true
